   0.0 TEL | Telepresence 0.93 launched at Mon Nov  5 17:09:03 2018
   0.0 TEL |   /usr/bin/telepresence --deployment tel
   0.0 TEL | Platform: linux
   0.0 TEL | Python 3.6.6 (default, Jul 19 2018, 14:25:17)
   0.0 TEL | [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
   0.0 TEL | [1] Running: uname -a
   0.0   1 | Linux localhost.localdomain 4.18.16-200.fc28.x86_64 #1 SMP Sat Oct 20 23:53:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   0.0 TEL | BEGIN SPAN main.py:41(main)
   0.0 TEL | BEGIN SPAN startup.py:58(__init__)
   0.0 TEL | [2] Capturing: kubectl version --short
   0.3 TEL | [3] Capturing: kubectl config current-context
   0.4 TEL | [4] Capturing: kubectl config view -o json
   0.4 TEL | [5] Capturing: kubectl get ns nemo
   0.5 TEL | Command: kubectl 1.12.2
   0.5 TEL | Context: nemo/127-0-0-1:8443/system:admin, namespace: nemo, version: 1.11.0+d4cacc0
   0.5 TEL | END SPAN startup.py:58(__init__)    0.5s
   0.5 TEL | [6] Capturing: ssh -V
   0.5 TEL | [7] Running: sudo -n echo -n
   0.5 >>> | Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
   0.5 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   0.5 TEL | [8] Capturing: kubectl --context nemo/127-0-0-1:8443/system:admin --namespace nemo get pods telepresence-connectivity-check --ignore-not-found
   1.7 TEL | Scout info: {'latest_version': '0.93', 'application': 'telepresence', 'notices': []}
   1.7 TEL | BEGIN SPAN remote.py:149(get_remote_info)
   1.7 TEL | BEGIN SPAN remote.py:73(get_deployment_json)
   1.7 TEL | [9] Capturing: kubectl --context nemo/127-0-0-1:8443/system:admin --namespace nemo get deployment -o json --export tel
   1.9 TEL | END SPAN remote.py:73(get_deployment_json)    0.2s
   1.9 TEL | Searching for Telepresence pod:
   1.9 TEL |   with name tel-*
   1.9 TEL |   with labels {'app': 'tel'}
   1.9 TEL | [10] Capturing: kubectl --context nemo/127-0-0-1:8443/system:admin --namespace nemo get pod -o json --export
   2.0 TEL | Checking identity-v0-5-7867b476fc-hq5r7
   2.0 TEL | --> Name does not match
   2.0 TEL | Checking pg-79d8c67d77-d74rn
   2.0 TEL | --> Name does not match
   2.0 TEL | Checking tel-75d469c475-qqfmb
   2.0 TEL | Looks like we've found our pod!
   2.0 TEL | BEGIN SPAN remote.py:111(wait_for_pod)
   2.0 TEL | [11] Capturing: kubectl --context nemo/127-0-0-1:8443/system:admin --namespace nemo get pod tel-75d469c475-qqfmb -o json
   2.1 TEL | END SPAN remote.py:111(wait_for_pod)    0.1s
   2.1 TEL | END SPAN remote.py:149(get_remote_info)    0.4s
   2.1 TEL | BEGIN SPAN __init__.py:38(connect)
   2.1 TEL | [12] Launching kubectl logs: kubectl --context nemo/127-0-0-1:8443/system:admin --namespace nemo logs -f tel-75d469c475-qqfmb --container telepresence
   2.1 TEL | [13] Launching kubectl port-forward: kubectl --context nemo/127-0-0-1:8443/system:admin --namespace nemo port-forward tel-75d469c475-qqfmb 37603:8022
   2.1 TEL | [14] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 37603 telepresence@localhost /bin/true
   2.1 TEL | [14] exit 255 in 0.01 secs.
   2.2  12 | Listening...
   2.2  12 | 2018-11-05T15:09:02+0000 [-] Loading ./forwarder.py...
   2.2  12 | 2018-11-05T15:09:04+0000 [-] /etc/resolv.conf changed, reparsing
   2.2  12 | 2018-11-05T15:09:04+0000 [-] Resolver added ('172.30.0.2', 53) to server list
   2.2  12 | 2018-11-05T15:09:04+0000 [-] SOCKSv5Factory starting on 9050
   2.2  12 | 2018-11-05T15:09:04+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7fa86739a710>
   2.2  12 | 2018-11-05T15:09:04+0000 [-] DNSDatagramProtocol starting on 9053
   2.2  12 | 2018-11-05T15:09:04+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86739aa90>
   2.2  12 | 2018-11-05T15:09:04+0000 [-] Loaded.
   2.2  12 | 2018-11-05T15:09:04+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.7.0 (/usr/bin/python3.6 3.6.5) starting up.
   2.2  12 | 2018-11-05T15:09:04+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
   2.2  13 | Forwarding from 127.0.0.1:37603 -> 8022
   2.2  13 | Forwarding from [::1]:37603 -> 8022
   2.4 TEL | [15] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 37603 telepresence@localhost /bin/true
   2.4  13 | Handling connection for 37603
   2.6 >>> | 
   2.6 >>> | No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.
   2.6 >>> | 
   2.6 TEL | Launching Web server for proxy poll
   2.6 TEL | [16] Launching SSH port forward (socks and proxy poll): ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 37603 telepresence@localhost -L127.0.0.1:33465:127.0.0.1:9050 -R9055:127.0.0.1:35509
   2.6 TEL | END SPAN __init__.py:38(connect)    0.5s
   2.6 TEL | BEGIN SPAN remote_env.py:65(get_remote_env)
   2.6 TEL | [17] Capturing: kubectl --context nemo/127-0-0-1:8443/system:admin --namespace nemo exec tel-75d469c475-qqfmb --container telepresence -- python3 -c 'import json, os; print(json.dumps(dict(os.environ)))'
   2.6  13 | Handling connection for 37603
   4.2 TEL | [17] captured in 1.65 secs.
   4.2 TEL | END SPAN remote_env.py:65(get_remote_env)    1.7s
   4.2 TEL | BEGIN SPAN mount.py:32(mount_remote_volumes)
   4.2 TEL | [18] Capturing: sshfs -p 37603 -F /dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null telepresence@localhost:/ /tmp/tel-5a5xgyv1/fs
   4.3  13 | Handling connection for 37603
   4.6 TEL | END SPAN mount.py:32(mount_remote_volumes)    0.3s
   4.6 TEL | BEGIN SPAN vpn.py:235(connect_sshuttle)
   4.6 TEL | BEGIN SPAN vpn.py:79(get_proxy_cidrs)
   4.6 TEL | END SPAN vpn.py:79(get_proxy_cidrs)    0.0s
   4.6 TEL | [19] Launching sshuttle: sshuttle-telepresence -v --dns --method nat -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence@localhost:37603 172.30.0.0/16
   4.6 TEL | BEGIN SPAN vpn.py:276(connect_sshuttle,sshuttle-wait)
   4.6 TEL | [20] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence0'"'"')'
   4.7  20 | Traceback (most recent call last):
   4.7  20 |   File "<string>", line 1, in <module>
   4.7  20 | socket.gaierror: [Errno -2] Name or service not known
   4.7 TEL | [20] exit 1 in 0.11 secs.
   4.8 TEL | [21] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence1'"'"')'
   4.9  21 | Traceback (most recent call last):
   4.9  21 |   File "<string>", line 1, in <module>
   4.9  21 | socket.gaierror: [Errno -2] Name or service not known
   4.9 TEL | [21] exit 1 in 0.10 secs.
   5.0  19 | Starting sshuttle proxy.
   5.1 TEL | [22] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence2'"'"')'
   5.2  22 | Traceback (most recent call last):
   5.2  22 |   File "<string>", line 1, in <module>
   5.2  22 | socket.gaierror: [Errno -2] Name or service not known
   5.2 TEL | [22] exit 1 in 0.09 secs.
   5.3 TEL | [23] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence3'"'"')'
   5.3  23 | Traceback (most recent call last):
   5.3  23 |   File "<string>", line 1, in <module>
   5.3  23 | socket.gaierror: [Errno -2] Name or service not known
   5.4 TEL | [23] exit 1 in 0.09 secs.
   5.4  19 | firewall manager: Starting firewall with Python version 3.6.6
   5.4  19 | firewall manager: ready method name nat.
   5.4  19 | IPv6 enabled: False
   5.4  19 | UDP enabled: False
   5.4  19 | DNS enabled: True
   5.4  19 | TCP redirector listening on ('127.0.0.1', 12300).
   5.4  19 | DNS listening on ('127.0.0.1', 12300).
   5.4  19 | Starting client with Python version 3.6.6
   5.4  19 | c : connecting to server...
   5.4  13 | Handling connection for 37603
   5.5  19 | Warning: Permanently added '[localhost]:37603' (ECDSA) to the list of known hosts.
   5.5 TEL | [24] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence4'"'"')'
   5.5  24 | Traceback (most recent call last):
   5.5  24 |   File "<string>", line 1, in <module>
   5.5  24 | socket.gaierror: [Errno -2] Name or service not known
   5.6 TEL | [24] exit 1 in 0.10 secs.
   5.7 TEL | [25] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence5'"'"')'
   5.8  25 | Traceback (most recent call last):
   5.8  25 |   File "<string>", line 1, in <module>
   5.8  25 | socket.gaierror: [Errno -2] Name or service not known
   5.8 TEL | [25] exit 1 in 0.12 secs.
   5.9 TEL | [26] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence6'"'"')'
   6.0  26 | Traceback (most recent call last):
   6.0  26 |   File "<string>", line 1, in <module>
   6.0  26 | socket.gaierror: [Errno -2] Name or service not known
   6.0 TEL | [26] exit 1 in 0.10 secs.
   6.1 TEL | [27] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence7'"'"')'
   6.2  27 | Traceback (most recent call last):
   6.2  27 |   File "<string>", line 1, in <module>
   6.2  27 | socket.gaierror: [Errno -2] Name or service not known
   6.2 TEL | [27] exit 1 in 0.12 secs.
   6.3  19 | Starting server with Python version 3.6.5
   6.3  19 |  s: latency control setting = True
   6.3  19 |  s: available routes:
   6.3  19 |  s:   2/172.17.0.0/16
   6.3  19 | c : Connected.
   6.3  19 | firewall manager: setting up.
   6.3  19 | >> iptables -t nat -N sshuttle-12300
   6.3 TEL | [28] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence8'"'"')'
   6.3  19 | >> iptables -t nat -F sshuttle-12300
   6.3  19 | >> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
   6.3  19 | >> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
   6.3  19 | >> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
   6.4  19 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 172.30.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
   6.4  19 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.100.102.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
   6.4  19 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 224.0.0.252/32 -p udp --dport 5355 --to-ports 12300 -m ttl ! --ttl 42
   6.4  28 | Traceback (most recent call last):
   6.4  28 |   File "<string>", line 1, in <module>
   6.4  28 | socket.gaierror: [Errno -2] Name or service not known
   6.4 TEL | [28] exit 1 in 0.15 secs.
   6.4  19 | conntrack v1.4.4 (conntrack-tools): 0 flow entries have been deleted.
   6.5  19 | c : DNS request from ('10.100.102.3', 53415) to None: 37 bytes
   6.5  19 | c : DNS request from ('10.100.102.3', 53415) to None: 37 bytes
   6.5  12 | 2018-11-05T15:09:09+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
   6.5  12 | 2018-11-05T15:09:09+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
   6.5  12 | 2018-11-05T15:09:09+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
   6.5 TEL | [29] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence9'"'"')'
   6.6  19 | c : DNS request from ('10.100.102.3', 43879) to None: 48 bytes
   6.6  12 | 2018-11-05T15:09:09+0000 [stdout#info] Set DNS suffix we filter out to: [(b'localdomain',)]
   6.6  12 | 2018-11-05T15:09:09+0000 [stdout#info] Result for b'hellotelepresence9.localdomain' is ['127.0.0.1']
   6.6 TEL | [30] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence10'"'"')'
   6.6  19 | c : DNS request from ('10.100.102.3', 42803) to None: 49 bytes
   6.6  12 | 2018-11-05T15:09:09+0000 [stdout#info] Result for b'hellotelepresence10.localdomain' is ['127.0.0.1']
   6.6 TEL | END SPAN vpn.py:276(connect_sshuttle,sshuttle-wait)    2.0s
   6.6 TEL | END SPAN vpn.py:235(connect_sshuttle)    2.1s
   6.6 TEL | Everything launched. Waiting to exit...
   6.6 TEL | BEGIN SPAN __init__.py:530(wait_for_exit)
  11.5  19 | c : DNS request from ('10.100.102.3', 53415) to None: 37 bytes
  11.5  19 | c : DNS request from ('10.100.102.3', 53415) to None: 37 bytes
  11.5  12 | 2018-11-05T15:09:14+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  11.5  12 | 2018-11-05T15:09:14+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
  11.5  12 | 2018-11-05T15:09:14+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  11.5  12 | 2018-11-05T15:09:14+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  11.5  12 | 2018-11-05T15:09:14+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  11.7  19 | c : DNS request from ('10.100.102.3', 40201) to None: 49 bytes
  11.7  19 | c : DNS request from ('10.100.102.3', 40201) to None: 49 bytes
  11.7  12 | 2018-11-05T15:09:14+0000 [stdout#info] Updated query of type 1 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  11.7  12 | 2018-11-05T15:09:14+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  11.7  12 | 2018-11-05T15:09:14+0000 [stdout#info] Updated query of type 28 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  11.7  12 | 2018-11-05T15:09:14+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
  11.7  12 | 2018-11-05T15:09:14+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  13.2  19 | c : DNS request from ('10.100.102.3', 53565) to None: 38 bytes
  13.2  12 | 2018-11-05T15:09:16+0000 [stdout#info] Updated query of type 1 from b'identity.localdomain' to b'identity'
  13.2  19 | c : Accept TCP: 10.100.102.3:42924 -> 172.30.25.237:80.
  13.2  12 | 2018-11-05T15:09:16+0000 [stdout#info] A query: b'identity'
  13.2  12 | 2018-11-05T15:09:16+0000 [stdout#info] Result for b'identity.localdomain' is ['172.30.25.237']
  16.6  12 | 2018-11-05T15:09:19+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  16.6  12 | 2018-11-05T15:09:19+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  16.7  19 | c : DNS request from ('10.100.102.3', 40201) to None: 49 bytes
  16.7  19 | c : DNS request from ('10.100.102.3', 40201) to None: 49 bytes
  16.7  12 | 2018-11-05T15:09:19+0000 [stdout#info] Updated query of type 1 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  16.7  12 | 2018-11-05T15:09:19+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  16.7  12 | 2018-11-05T15:09:19+0000 [stdout#info] Updated query of type 28 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  16.7  12 | 2018-11-05T15:09:19+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
  16.8  12 | 2018-11-05T15:09:20+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  16.8  12 | 2018-11-05T15:09:20+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  16.8  12 | 2018-11-05T15:09:20+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  16.8  12 | 2018-11-05T15:09:20+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  16.8  12 | 2018-11-05T15:09:20+0000 [-] DNSDatagramProtocol starting on 5780
  16.8  12 | 2018-11-05T15:09:20+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867364080>
  16.9  12 | 2018-11-05T15:09:20+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  16.9  12 | 2018-11-05T15:09:20+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  16.9  12 | 2018-11-05T15:09:20+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  16.9  12 | 2018-11-05T15:09:20+0000 [-] DNSDatagramProtocol starting on 61668
  16.9  12 | 2018-11-05T15:09:20+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86733c358>
  17.8  12 | 2018-11-05T15:09:21+0000 [-] DNSDatagramProtocol starting on 13932
  17.8  12 | 2018-11-05T15:09:21+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354780>
  17.8  12 | 2018-11-05T15:09:21+0000 [-] (UDP Port 5780 Closed)
  17.8  12 | 2018-11-05T15:09:21+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867364080>
  17.9  12 | 2018-11-05T15:09:21+0000 [-] DNSDatagramProtocol starting on 35656
  17.9  12 | 2018-11-05T15:09:21+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354668>
  17.9  12 | 2018-11-05T15:09:21+0000 [-] (UDP Port 61668 Closed)
  17.9  12 | 2018-11-05T15:09:21+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86733c358>
  20.8  12 | 2018-11-05T15:09:24+0000 [-] DNSDatagramProtocol starting on 35170
  20.8  12 | 2018-11-05T15:09:24+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354710>
  20.8  12 | 2018-11-05T15:09:24+0000 [-] (UDP Port 13932 Closed)
  20.8  12 | 2018-11-05T15:09:24+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354780>
  20.9  12 | 2018-11-05T15:09:24+0000 [-] DNSDatagramProtocol starting on 4147
  20.9  12 | 2018-11-05T15:09:24+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354780>
  20.9  12 | 2018-11-05T15:09:24+0000 [-] (UDP Port 35656 Closed)
  20.9  12 | 2018-11-05T15:09:24+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354668>
  21.8  12 | 2018-11-05T15:09:25+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  21.8  12 | 2018-11-05T15:09:25+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  21.8  12 | 2018-11-05T15:09:25+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  21.8  12 | 2018-11-05T15:09:25+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  21.8  12 | 2018-11-05T15:09:25+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  21.8  12 | 2018-11-05T15:09:25+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  25.5  19 | c : DNS request from ('10.100.102.3', 53086) to None: 37 bytes
  25.5  12 | 2018-11-05T15:09:28+0000 [stdout#info] A query: b'clients4.google.com'
  26.7  19 | c : DNS request from ('10.100.102.3', 34424) to None: 57 bytes
  26.7  12 | 2018-11-05T15:09:30+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  29.9  19 | c : Accept TCP: 10.100.102.3:60684 -> 172.30.249.217:443.
  29.9  19 | c : Accept TCP: 10.100.102.3:60690 -> 172.30.249.217:443.
  29.9  19 | c : Accept TCP: 10.100.102.3:60696 -> 172.30.249.217:443.
  29.9  19 | c : Accept TCP: 10.100.102.3:60698 -> 172.30.249.217:443.
  29.9  19 | c : Accept TCP: 10.100.102.3:60700 -> 172.30.249.217:443.
  30.1  19 | c : Accept TCP: 10.100.102.3:60714 -> 172.30.249.217:443.
  30.2  19 | c : Accept TCP: 10.100.102.3:60722 -> 172.30.249.217:443.
  30.3  19 | c : SW#10:10.100.102.3:60684: uwrite: got EPIPE
  30.3  19 | c : SW#11:10.100.102.3:60690: deleting (15 remain)
  30.3  19 | c : SW#11:10.100.102.3:60690: error was: uread: [Errno 104] Connection reset by peer
  30.3  19 | c : SW'unknown':Mux#16: deleting (14 remain)
  30.3  19 | c : SW#10:10.100.102.3:60684: deleting (13 remain)
  30.3  19 | c : SW#10:10.100.102.3:60684: error was: nowrite: [Errno 107] Transport endpoint is not connected
  30.3  19 | c : SW'unknown':Mux#15: deleting (12 remain)
  30.3  19 | c : Accept TCP: 10.100.102.3:60728 -> 172.30.249.217:443.
  30.4  19 | c : Accept TCP: 10.100.102.3:60742 -> 172.30.249.217:443.
  30.5  19 | c : SW#12:10.100.102.3:60696: deleting (15 remain)
  30.5  19 | c : SW#12:10.100.102.3:60696: error was: uread: [Errno 104] Connection reset by peer
  30.5  19 | c : SW'unknown':Mux#17: deleting (14 remain)
  30.5  19 | c : DNS request from ('10.100.102.3', 53086) to None: 37 bytes
  30.5  19 | c : Accept TCP: 10.100.102.3:60748 -> 172.30.249.217:443.
  30.6  19 | c : SW#13:10.100.102.3:60698: uwrite: got EPIPE
  30.6  12 | 2018-11-05T15:09:33+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  30.6 TEL | [31] Running: sudo -n echo -n
  30.6  12 | 2018-11-05T15:09:33+0000 [stdout#info] A query: b'clients4.google.com'
  30.7  19 |  s: SW'unknown':Mux#15: deleting (19 remain)
  30.7  19 |  s: SW#15:172.30.249.217:443: deleting (18 remain)
  30.7  19 |  s: SW'unknown':Mux#16: deleting (17 remain)
  30.7  19 |  s: SW#16:172.30.249.217:443: deleting (16 remain)
  30.7  19 |  s: SW'unknown':Mux#17: deleting (15 remain)
  30.7  19 |  s: SW#17:172.30.249.217:443: deleting (14 remain)
  30.7  19 | c : warning: closed channel 18 got cmd=TCP_EOF len=0
  30.7  19 |  s: warning: closed channel 18 got cmd=TCP_STOP_SENDING len=0
  30.7  19 | c : SW#14:10.100.102.3:60700: deleting (15 remain)
  30.7  19 | c : SW#14:10.100.102.3:60700: error was: uread: [Errno 104] Connection reset by peer
  30.7  19 | c : SW'unknown':Mux#19: deleting (14 remain)
  30.7  19 | c : SW#13:10.100.102.3:60698: deleting (13 remain)
  30.7  19 | c : SW#13:10.100.102.3:60698: error was: nowrite: [Errno 107] Transport endpoint is not connected
  30.7  19 | c : SW'unknown':Mux#18: deleting (12 remain)
  30.7  19 | c : DNS request from ('10.100.102.3', 34662) to None: 49 bytes
  30.8  12 | 2018-11-05T15:09:34+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  30.8  12 | 2018-11-05T15:09:34+0000 [stdout#info] A query: b'clients4.google.com'
  30.9  19 | c : Accept TCP: 10.100.102.3:60762 -> 172.30.249.217:443.
  30.9  19 | c : Accept TCP: 10.100.102.3:60764 -> 172.30.249.217:443.
  31.0  19 | c : warning: closed channel 20 got cmd=TCP_DATA len=31
  31.0  19 | c : SW#15:10.100.102.3:60714: deleting (15 remain)
  31.0  19 | c : SW#15:10.100.102.3:60714: error was: uread: [Errno 104] Connection reset by peer
  31.0  19 | c : SW'unknown':Mux#20: deleting (14 remain)
  31.1  19 | c : SW#16:10.100.102.3:60722: uwrite: got EPIPE
  31.2  19 |  s: SW'unknown':Mux#19: deleting (19 remain)
  31.2  19 |  s: SW#19:172.30.249.217:443: deleting (18 remain)
  31.2  19 | c : warning: closed channel 21 got cmd=TCP_EOF len=0
  31.2  19 |  s: SW'unknown':Mux#21: deleting (17 remain)
  31.2  19 |  s: SW#9:172.30.249.217:443: deleting (16 remain)
  31.2  19 |  s: warning: closed channel 21 got cmd=TCP_STOP_SENDING len=0
  31.2  19 | c : SW#10:10.100.102.3:60728: uwrite: got EPIPE
  31.2  19 | c : warning: closed channel 22 got cmd=TCP_EOF len=0
  31.3  19 |  s: warning: closed channel 22 got cmd=TCP_STOP_SENDING len=0
  31.3  19 | c : SW#11:10.100.102.3:60742: uwrite: got EPIPE
  31.3  19 | c : warning: closed channel 23 got cmd=TCP_EOF len=0
  31.3  19 | c : SW#16:10.100.102.3:60722: deleting (13 remain)
  31.3  19 | c : SW#16:10.100.102.3:60722: error was: nowrite: [Errno 107] Transport endpoint is not connected
  31.3  19 | c : SW'unknown':Mux#21: deleting (12 remain)
  31.3  19 | c : SW#10:10.100.102.3:60728: deleting (11 remain)
  31.3  19 | c : SW#10:10.100.102.3:60728: error was: nowrite: [Errno 107] Transport endpoint is not connected
  31.3  19 | c : SW'unknown':Mux#22: deleting (10 remain)
  31.4  19 |  s: warning: closed channel 23 got cmd=TCP_STOP_SENDING len=0
  31.5  19 | c : SW#14:10.100.102.3:60764: uwrite: got EPIPE
  31.5  19 | c : DNS request from ('10.100.102.3', 42753) to None: 37 bytes
  31.5  12 | 2018-11-05T15:09:34+0000 [stdout#info] A query: b'clients4.google.com'
  31.7 TEL | (proxy checking local liveness)
  31.7  12 | 2018-11-05T15:09:34+0000 [Poll#info] Checkpoint
  31.8  19 | c : DNS request from ('10.100.102.3', 34424) to None: 57 bytes
  31.9  12 | 2018-11-05T15:09:35+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  31.9  12 | 2018-11-05T15:09:35+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  31.9  12 | 2018-11-05T15:09:35+0000 [-] DNSDatagramProtocol starting on 19735
  31.9  12 | 2018-11-05T15:09:35+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354668>
  31.9  12 | 2018-11-05T15:09:35+0000 [-] (UDP Port 35170 Closed)
  31.9  12 | 2018-11-05T15:09:35+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354710>
  31.9  19 | c : DNS request from ('10.100.102.3', 42707) to None: 69 bytes
  31.9  12 | 2018-11-05T15:09:35+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  31.9  12 | 2018-11-05T15:09:35+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  31.9  12 | 2018-11-05T15:09:35+0000 [-] DNSDatagramProtocol starting on 52278
  32.0  12 | 2018-11-05T15:09:35+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672e58d0>
  32.0  12 | 2018-11-05T15:09:35+0000 [-] (UDP Port 4147 Closed)
  32.0  12 | 2018-11-05T15:09:35+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354780>
  32.7  19 | c : DNS request from ('10.100.102.3', 37030) to None: 57 bytes
  32.7  12 | 2018-11-05T15:09:36+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  35.7  19 | c : DNS request from ('10.100.102.3', 34662) to None: 49 bytes
  35.7  12 | 2018-11-05T15:09:38+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  35.7  12 | 2018-11-05T15:09:38+0000 [stdout#info] A query: b'clients4.google.com'
  35.8  12 | 2018-11-05T15:09:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  36.0  12 | 2018-11-05T15:09:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  36.0  12 | 2018-11-05T15:09:39+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  36.0  12 | 2018-11-05T15:09:39+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  36.0  12 | 2018-11-05T15:09:39+0000 [-] DNSDatagramProtocol starting on 34609
  36.0  12 | 2018-11-05T15:09:39+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8673546a0>
  36.5  19 | c : DNS request from ('10.100.102.3', 42753) to None: 37 bytes
  36.5  12 | 2018-11-05T15:09:39+0000 [stdout#info] A query: b'clients4.google.com'
  36.6  12 | 2018-11-05T15:09:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  36.6  19 | c : DNS request from ('10.100.102.3', 54309) to None: 49 bytes
  36.7  12 | 2018-11-05T15:09:39+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  36.7  12 | 2018-11-05T15:09:39+0000 [stdout#info] A query: b'clients4.google.com'
  36.9  12 | 2018-11-05T15:09:40+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  36.9  19 | c : DNS request from ('10.100.102.3', 42707) to None: 69 bytes
  36.9  12 | 2018-11-05T15:09:40+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  36.9  12 | 2018-11-05T15:09:40+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  37.0  12 | 2018-11-05T15:09:40+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  37.0  12 | 2018-11-05T15:09:40+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  37.0  12 | 2018-11-05T15:09:40+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  37.0  12 | 2018-11-05T15:09:40+0000 [-] DNSDatagramProtocol starting on 22086
  37.0  12 | 2018-11-05T15:09:40+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867276a20>
  37.0  12 | 2018-11-05T15:09:40+0000 [-] DNSDatagramProtocol starting on 28083
  37.0  12 | 2018-11-05T15:09:40+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867364c88>
  37.0  12 | 2018-11-05T15:09:40+0000 [-] (UDP Port 34609 Closed)
  37.0  12 | 2018-11-05T15:09:40+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8673546a0>
  37.8  19 | c : DNS request from ('10.100.102.3', 37030) to None: 57 bytes
  37.8  12 | 2018-11-05T15:09:41+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  37.8  19 | c : DNS request from ('10.100.102.3', 33082) to None: 69 bytes
  37.8  12 | 2018-11-05T15:09:41+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  37.8  12 | 2018-11-05T15:09:41+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  37.8  12 | 2018-11-05T15:09:41+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  38.0  12 | 2018-11-05T15:09:41+0000 [-] DNSDatagramProtocol starting on 24051
  38.0  12 | 2018-11-05T15:09:41+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867276eb8>
  38.0  12 | 2018-11-05T15:09:41+0000 [-] (UDP Port 22086 Closed)
  38.0  12 | 2018-11-05T15:09:41+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867276a20>
  39.3  19 | c : DNS request from ('10.100.102.3', 39148) to None: 43 bytes
  39.3  19 | c : DNS request from ('10.100.102.3', 39148) to None: 43 bytes
  39.3  12 | 2018-11-05T15:09:42+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  39.3  12 | 2018-11-05T15:09:42+0000 [stdout#info] AAAA query, sending back A instead: b'vortex.data.microsoft.com'
  39.3  12 | 2018-11-05T15:09:42+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  40.0  12 | 2018-11-05T15:09:43+0000 [-] DNSDatagramProtocol starting on 15248
  40.0  12 | 2018-11-05T15:09:43+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867280550>
  40.0  12 | 2018-11-05T15:09:43+0000 [-] (UDP Port 28083 Closed)
  40.0  12 | 2018-11-05T15:09:43+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867364c88>
  40.7  19 | c : DNS request from ('10.100.102.3', 52331) to None: 37 bytes
  40.7  12 | 2018-11-05T15:09:44+0000 [stdout#info] A query: b'clients4.google.com'
  40.7  12 | 2018-11-05T15:09:44+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  40.7  12 | 2018-11-05T15:09:44+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  40.7  12 | 2018-11-05T15:09:44+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  41.0  12 | 2018-11-05T15:09:44+0000 [-] DNSDatagramProtocol starting on 49676
  41.0  12 | 2018-11-05T15:09:44+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672e5e10>
  41.0  12 | 2018-11-05T15:09:44+0000 [-] (UDP Port 24051 Closed)
  41.0  12 | 2018-11-05T15:09:44+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867276eb8>
  41.5  12 | 2018-11-05T15:09:44+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  41.6  19 | c : DNS request from ('10.100.102.3', 54309) to None: 49 bytes
  41.6  12 | 2018-11-05T15:09:44+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  41.6  12 | 2018-11-05T15:09:44+0000 [stdout#info] A query: b'clients4.google.com'
  41.7  12 | 2018-11-05T15:09:44+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  41.7  12 | 2018-11-05T15:09:44+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  41.7  12 | 2018-11-05T15:09:44+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  41.9  12 | 2018-11-05T15:09:45+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  41.9  12 | 2018-11-05T15:09:45+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  41.9  12 | 2018-11-05T15:09:45+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  42.8  19 | c : DNS request from ('10.100.102.3', 33082) to None: 69 bytes
  42.9  19 |  s: SW'unknown':Mux#22: deleting (15 remain)
  42.9  19 |  s: SW#20:172.30.249.217:443: deleting (14 remain)
  42.9  19 |  s: SW'unknown':Mux#23: deleting (13 remain)
  42.9  19 |  s: SW#21:172.30.249.217:443: deleting (12 remain)
  42.9  19 |  s: SW'unknown':Mux#27: deleting (11 remain)
  42.9  19 |  s: SW#17:172.30.249.217:443: deleting (10 remain)
  42.9  12 | 2018-11-05T15:09:46+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  42.9  12 | 2018-11-05T15:09:46+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  42.9  12 | 2018-11-05T15:09:46+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  42.9  12 | 2018-11-05T15:09:46+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  42.9  12 | 2018-11-05T15:09:46+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  42.9  12 | 2018-11-05T15:09:46+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  43.5  19 | c : DNS request from ('10.100.102.3', 49411) to None: 57 bytes
  43.5  12 | 2018-11-05T15:09:46+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  44.3  19 | c : DNS request from ('10.100.102.3', 39148) to None: 43 bytes
  44.3  19 | c : DNS request from ('10.100.102.3', 39148) to None: 43 bytes
  44.3  19 | c : SW#12:10.100.102.3:60748: deleting (9 remain)
  44.3  19 | c : SW#12:10.100.102.3:60748: error was: uread: [Errno 104] Connection reset by peer
  44.3  19 | c : SW'unknown':Mux#25: deleting (8 remain)
  44.3  12 | 2018-11-05T15:09:47+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  44.3  12 | 2018-11-05T15:09:47+0000 [stdout#info] AAAA query, sending back A instead: b'vortex.data.microsoft.com'
  44.3  19 | c : DNS request from ('10.100.102.3', 41602) to None: 55 bytes
  44.3  19 | c : DNS request from ('10.100.102.3', 41602) to None: 55 bytes
  44.3  12 | 2018-11-05T15:09:47+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  44.3  12 | 2018-11-05T15:09:47+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  44.3  12 | 2018-11-05T15:09:47+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  44.3  12 | 2018-11-05T15:09:47+0000 [stdout#info] Updated query of type 1 from b'vortex.data.microsoft.com.localdomain' to b'vortex.data.microsoft.com'
  44.3  12 | 2018-11-05T15:09:47+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  44.4  12 | 2018-11-05T15:09:47+0000 [stdout#info] Updated query of type 28 from b'vortex.data.microsoft.com.localdomain' to b'vortex.data.microsoft.com'
  44.4  12 | 2018-11-05T15:09:47+0000 [stdout#info] AAAA query, sending back A instead: b'vortex.data.microsoft.com'
  44.4  12 | 2018-11-05T15:09:47+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  45.7  19 | c : DNS request from ('10.100.102.3', 52331) to None: 37 bytes
  45.7  12 | 2018-11-05T15:09:49+0000 [stdout#info] A query: b'clients4.google.com'
  45.7  19 | c : DNS request from ('10.100.102.3', 37757) to None: 49 bytes
  45.7  12 | 2018-11-05T15:09:49+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  45.7  12 | 2018-11-05T15:09:49+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  45.7  12 | 2018-11-05T15:09:49+0000 [stdout#info] A query: b'clients4.google.com'
  46.6  12 | 2018-11-05T15:09:49+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  46.6  12 | 2018-11-05T15:09:49+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  46.6  12 | 2018-11-05T15:09:49+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  46.7  19 | c : DNS request from ('10.100.102.3', 45463) to None: 37 bytes
  46.7  12 | 2018-11-05T15:09:50+0000 [stdout#info] A query: b'clients4.google.com'
  47.5  19 | c : DNS request from ('10.100.102.3', 35399) to None: 34 bytes
  47.5  12 | 2018-11-05T15:09:50+0000 [stdout#info] A query: b'api.mixpanel.com'
  47.5  19 | c : DNS request from ('10.100.102.3', 60219) to None: 41 bytes
  47.5  12 | 2018-11-05T15:09:50+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  47.9  12 | 2018-11-05T15:09:51+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  47.9  12 | 2018-11-05T15:09:51+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  47.9  12 | 2018-11-05T15:09:51+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  48.5  19 | c : DNS request from ('10.100.102.3', 49411) to None: 57 bytes
  48.5  12 | 2018-11-05T15:09:51+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  48.5  19 | c : DNS request from ('10.100.102.3', 48408) to None: 69 bytes
  48.5  12 | 2018-11-05T15:09:51+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  48.5  12 | 2018-11-05T15:09:51+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  48.5  12 | 2018-11-05T15:09:51+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  49.3  12 | 2018-11-05T15:09:52+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  49.4  19 | c : DNS request from ('10.100.102.3', 41602) to None: 55 bytes
  49.4  19 | c : DNS request from ('10.100.102.3', 41602) to None: 55 bytes
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] Updated query of type 1 from b'vortex.data.microsoft.com.localdomain' to b'vortex.data.microsoft.com'
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] Updated query of type 28 from b'vortex.data.microsoft.com.localdomain' to b'vortex.data.microsoft.com'
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] AAAA query, sending back A instead: b'vortex.data.microsoft.com'
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] A query: b'vortex.data.microsoft.com'
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] Failed to lookup b'vortex.data.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  49.4  12 | 2018-11-05T15:09:52+0000 [stdout#info] ], falling back to b'vortex.data.microsoft.com.localdomain'
  49.4  12 | 2018-11-05T15:09:52+0000 [-] DNSDatagramProtocol starting on 31008
  49.4  12 | 2018-11-05T15:09:52+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729dbe0>
  49.5  12 | 2018-11-05T15:09:52+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  49.5  19 | c : DNS request from ('10.100.102.3', 58746) to None: 57 bytes
  49.5  12 | 2018-11-05T15:09:52+0000 [stdout#info] Failed to lookup b'vortex.data.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  49.5  12 | 2018-11-05T15:09:52+0000 [stdout#info] ], falling back to b'vortex.data.microsoft.com.localdomain'
  49.5  12 | 2018-11-05T15:09:52+0000 [-] DNSDatagramProtocol starting on 7226
  49.5  12 | 2018-11-05T15:09:52+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867276f28>
  49.5  12 | 2018-11-05T15:09:52+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  50.4  12 | 2018-11-05T15:09:53+0000 [-] DNSDatagramProtocol starting on 12736
  50.4  12 | 2018-11-05T15:09:53+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729deb8>
  50.4  12 | 2018-11-05T15:09:53+0000 [-] (UDP Port 31008 Closed)
  50.4  12 | 2018-11-05T15:09:53+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729dbe0>
  50.5  12 | 2018-11-05T15:09:53+0000 [-] DNSDatagramProtocol starting on 7157
  50.5  12 | 2018-11-05T15:09:53+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729dcc0>
  50.5  12 | 2018-11-05T15:09:53+0000 [-] (UDP Port 7226 Closed)
  50.5  12 | 2018-11-05T15:09:53+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867276f28>
  50.7  12 | 2018-11-05T15:09:54+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  50.7  19 | c : DNS request from ('10.100.102.3', 37757) to None: 49 bytes
  50.7  12 | 2018-11-05T15:09:54+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  50.7  12 | 2018-11-05T15:09:54+0000 [stdout#info] A query: b'clients4.google.com'
  50.7  12 | 2018-11-05T15:09:54+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  50.7  12 | 2018-11-05T15:09:54+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  50.7  12 | 2018-11-05T15:09:54+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  51.0  12 | 2018-11-05T15:09:54+0000 [-] DNSDatagramProtocol starting on 22971
  51.0  12 | 2018-11-05T15:09:54+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e6a0>
  51.0  12 | 2018-11-05T15:09:54+0000 [-] (UDP Port 15248 Closed)
  51.0  12 | 2018-11-05T15:09:54+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867280550>
  51.7  19 | c : DNS request from ('10.100.102.3', 45463) to None: 37 bytes
  51.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] A query: b'clients4.google.com'
  51.7  19 | c : DNS request from ('10.100.102.3', 35460) to None: 49 bytes
  51.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  51.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  51.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] A query: b'clients4.google.com'
  52.0  12 | 2018-11-05T15:09:55+0000 [-] DNSDatagramProtocol starting on 50155
  52.0  12 | 2018-11-05T15:09:55+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672ab828>
  52.0  12 | 2018-11-05T15:09:55+0000 [-] (UDP Port 49676 Closed)
  52.0  12 | 2018-11-05T15:09:55+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672e5e10>
  52.5  19 | c : DNS request from ('10.100.102.3', 35399) to None: 34 bytes
  52.5  12 | 2018-11-05T15:09:55+0000 [stdout#info] A query: b'api.mixpanel.com'
  52.5  19 | c : DNS request from ('10.100.102.3', 60219) to None: 41 bytes
  52.5  12 | 2018-11-05T15:09:55+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  52.5  12 | 2018-11-05T15:09:55+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  52.6  12 | 2018-11-05T15:09:55+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  52.6  19 | c : DNS request from ('10.100.102.3', 44020) to None: 46 bytes
  52.6  19 | c : DNS request from ('10.100.102.3', 52230) to None: 53 bytes
  52.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] Updated query of type 1 from b'api.mixpanel.com.localdomain' to b'api.mixpanel.com'
  52.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] A query: b'api.mixpanel.com'
  52.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] Updated query of type 1 from b'www.msftconnecttest.com.localdomain' to b'www.msftconnecttest.com'
  52.7  12 | 2018-11-05T15:09:55+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  53.4  12 | 2018-11-05T15:09:56+0000 [-] DNSDatagramProtocol starting on 43024
  53.4  12 | 2018-11-05T15:09:56+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ad358>
  53.4  12 | 2018-11-05T15:09:56+0000 [-] (UDP Port 12736 Closed)
  53.4  12 | 2018-11-05T15:09:56+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729deb8>
  53.5  19 | c : DNS request from ('10.100.102.3', 41579) to None: 41 bytes
  53.5  12 | 2018-11-05T15:09:56+0000 [-] DNSDatagramProtocol starting on 1689
  53.5  12 | 2018-11-05T15:09:56+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672ab160>
  53.5  12 | 2018-11-05T15:09:56+0000 [-] (UDP Port 7157 Closed)
  53.5  12 | 2018-11-05T15:09:56+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729dcc0>
  53.5  12 | 2018-11-05T15:09:56+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  53.5  19 | c : DNS request from ('10.100.102.3', 48408) to None: 69 bytes
  53.5  12 | 2018-11-05T15:09:56+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  53.6  12 | 2018-11-05T15:09:56+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  53.6  12 | 2018-11-05T15:09:56+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  53.6  12 | 2018-11-05T15:09:56+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  53.6  12 | 2018-11-05T15:09:56+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  53.6  12 | 2018-11-05T15:09:56+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  54.4  12 | 2018-11-05T15:09:57+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  54.4  12 | 2018-11-05T15:09:57+0000 [stdout#info] Failed to lookup b'vortex.data.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  54.4  12 | 2018-11-05T15:09:57+0000 [stdout#info] ], falling back to b'vortex.data.microsoft.com.localdomain'
  54.5  12 | 2018-11-05T15:09:57+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  54.5  12 | 2018-11-05T15:09:57+0000 [stdout#info] Failed to lookup b'vortex.data.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  54.5  12 | 2018-11-05T15:09:57+0000 [stdout#info] ], falling back to b'vortex.data.microsoft.com.localdomain'
  54.5  19 | c : DNS request from ('10.100.102.3', 58746) to None: 57 bytes
  54.5  12 | 2018-11-05T15:09:57+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  54.5  12 | 2018-11-05T15:09:57+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  54.5  19 | c : DNS request from ('10.100.102.3', 36228) to None: 69 bytes
  54.5  12 | 2018-11-05T15:09:57+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  54.5  12 | 2018-11-05T15:09:57+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  55.7  12 | 2018-11-05T15:09:59+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  55.7  12 | 2018-11-05T15:09:59+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  55.7  12 | 2018-11-05T15:09:59+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  56.7  19 | c : DNS request from ('10.100.102.3', 35460) to None: 49 bytes
  56.7  12 | 2018-11-05T15:10:00+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  56.7  12 | 2018-11-05T15:10:00+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
  56.8  12 | 2018-11-05T15:10:00+0000 [stdout#info] A query: b'clients4.google.com'
  56.8  12 | 2018-11-05T15:10:00+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  56.8  12 | 2018-11-05T15:10:00+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  56.8  12 | 2018-11-05T15:10:00+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  57.5  12 | 2018-11-05T15:10:00+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  57.5  12 | 2018-11-05T15:10:00+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  57.6  19 | c : DNS request from ('10.100.102.3', 44020) to None: 46 bytes
  57.6  19 | c : DNS request from ('10.100.102.3', 52230) to None: 53 bytes
  57.6  12 | 2018-11-05T15:10:00+0000 [stdout#info] Updated query of type 1 from b'api.mixpanel.com.localdomain' to b'api.mixpanel.com'
  57.6  12 | 2018-11-05T15:10:00+0000 [stdout#info] A query: b'api.mixpanel.com'
  57.7  12 | 2018-11-05T15:10:00+0000 [stdout#info] Updated query of type 1 from b'www.msftconnecttest.com.localdomain' to b'www.msftconnecttest.com'
  57.7  12 | 2018-11-05T15:10:00+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  57.7  12 | 2018-11-05T15:10:00+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  57.7  12 | 2018-11-05T15:10:00+0000 [stdout#info] Failed to lookup b'api.mixpanel.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  57.7  12 | 2018-11-05T15:10:00+0000 [stdout#info] ], falling back to b'api.mixpanel.com.localdomain'
  57.7  12 | 2018-11-05T15:10:00+0000 [-] DNSDatagramProtocol starting on 49826
  57.7  12 | 2018-11-05T15:10:00+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bb358>
  57.8  12 | 2018-11-05T15:10:01+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  57.8  12 | 2018-11-05T15:10:01+0000 [stdout#info] Failed to lookup b'www.msftconnecttest.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  57.8  12 | 2018-11-05T15:10:01+0000 [stdout#info] ], falling back to b'www.msftconnecttest.com.localdomain'
  57.8  12 | 2018-11-05T15:10:01+0000 [-] DNSDatagramProtocol starting on 31100
  57.8  12 | 2018-11-05T15:10:01+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e9e8>
  58.5  19 | c : DNS request from ('10.100.102.3', 41579) to None: 41 bytes
  58.5  12 | 2018-11-05T15:10:01+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  58.6  12 | 2018-11-05T15:10:01+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  58.6  19 | c : DNS request from ('10.100.102.3', 43114) to None: 53 bytes
  58.6  12 | 2018-11-05T15:10:01+0000 [stdout#info] Updated query of type 1 from b'www.msftconnecttest.com.localdomain' to b'www.msftconnecttest.com'
  58.6  12 | 2018-11-05T15:10:01+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  58.7  12 | 2018-11-05T15:10:01+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  58.7  12 | 2018-11-05T15:10:01+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  58.7  12 | 2018-11-05T15:10:01+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  58.7  12 | 2018-11-05T15:10:01+0000 [-] DNSDatagramProtocol starting on 14547
  58.7  12 | 2018-11-05T15:10:01+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ada90>
  58.7  12 | 2018-11-05T15:10:01+0000 [-] (UDP Port 49826 Closed)
  58.7  12 | 2018-11-05T15:10:01+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bb358>
  58.8  12 | 2018-11-05T15:10:02+0000 [-] DNSDatagramProtocol starting on 42972
  58.8  12 | 2018-11-05T15:10:02+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ad978>
  58.8  12 | 2018-11-05T15:10:02+0000 [-] (UDP Port 31100 Closed)
  58.8  12 | 2018-11-05T15:10:02+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e9e8>
  59.5  12 | 2018-11-05T15:10:02+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  59.5  19 | c : DNS request from ('10.100.102.3', 36228) to None: 69 bytes
  59.5  12 | 2018-11-05T15:10:02+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  59.5  12 | 2018-11-05T15:10:02+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  59.6  12 | 2018-11-05T15:10:02+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  59.6  12 | 2018-11-05T15:10:02+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  59.6  12 | 2018-11-05T15:10:02+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  59.9  19 | c : Accept TCP: 10.100.102.3:32910 -> 172.30.249.217:443.
  59.9  19 | c : Accept TCP: 10.100.102.3:32912 -> 172.30.249.217:443.
  59.9  19 | c : Accept TCP: 10.100.102.3:32922 -> 172.30.249.217:443.
  59.9  19 | c : Accept TCP: 10.100.102.3:32924 -> 172.30.249.217:443.
  60.0  19 | c : Accept TCP: 10.100.102.3:32934 -> 172.30.249.217:443.
  60.4  19 | c : Accept TCP: 10.100.102.3:32940 -> 172.30.249.217:443.
  60.4  19 | c : Accept TCP: 10.100.102.3:32942 -> 172.30.249.217:443.
  60.5  19 | c : Accept TCP: 10.100.102.3:32960 -> 172.30.249.217:443.
  60.5  19 | c : Accept TCP: 10.100.102.3:32962 -> 172.30.249.217:443.
  60.6  19 | c : SW#10:10.100.102.3:32910: uwrite: got EPIPE
  60.6  19 | c : Accept TCP: 10.100.102.3:32972 -> 172.30.249.217:443.
  60.7  19 | c : SW#12:10.100.102.3:32912: uwrite: got EPIPE
  60.7  19 | c : warning: closed channel 77 got cmd=TCP_EOF len=0
  60.7  19 |  s: warning: closed channel 77 got cmd=TCP_STOP_SENDING len=0
  60.7 TEL | [32] Running: sudo -n echo -n
  60.8  19 | c : SW#16:10.100.102.3:32924: uwrite: got EPIPE
  60.8  19 | c : SW#17:10.100.102.3:32934: deleting (27 remain)
  60.8  19 | c : SW#17:10.100.102.3:32934: error was: uread: [Errno 104] Connection reset by peer
  60.8  19 | c : SW'unknown':Mux#80: deleting (26 remain)
  60.8  19 | c : SW'unknown':Mux#76: deleting (25 remain)
  60.8  19 | c : SW#10:10.100.102.3:32910: deleting (24 remain)
  60.8  19 | c : SW#10:10.100.102.3:32910: error was: nowrite: [Errno 107] Transport endpoint is not connected
  60.9  19 |  s: SW'unknown':Mux#77: deleting (29 remain)
  60.9  19 |  s: SW#60:172.30.249.217:443: deleting (28 remain)
  60.9  19 |  s: SW'unknown':Mux#76: deleting (27 remain)
  60.9  19 |  s: SW#59:172.30.249.217:443: deleting (26 remain)
  60.9  19 |  s: SW'unknown':Mux#79: deleting (25 remain)
  60.9  19 |  s: SW#62:172.30.249.217:443: deleting (24 remain)
  60.9  19 |  s: SW'unknown':Mux#78: deleting (23 remain)
  60.9  19 |  s: SW#61:172.30.249.217:443: deleting (22 remain)
  60.9  19 |  s: SW'unknown':Mux#80: deleting (21 remain)
  60.9  19 |  s: SW#6:172.30.249.217:443: deleting (20 remain)
  61.1  19 | c : Accept TCP: 10.100.102.3:32988 -> 172.30.249.217:443.
  61.2  19 | c : Accept TCP: 10.100.102.3:32994 -> 172.30.249.217:443.
  61.3  19 | c : SW#20:10.100.102.3:32960: deleting (27 remain)
  61.3  19 | c : SW#20:10.100.102.3:32960: error was: uread: [Errno 104] Connection reset by peer
  61.3  19 | c : SW'unknown':Mux#83: deleting (26 remain)
  61.3  19 | c : SW#19:10.100.102.3:32942: deleting (25 remain)
  61.3  19 | c : SW#19:10.100.102.3:32942: error was: uread: [Errno 104] Connection reset by peer
  61.3  19 | c : SW'unknown':Mux#82: deleting (24 remain)
  61.3  19 |  s: SW'unknown':Mux#81: deleting (23 remain)
  61.3  19 |  s: SW#7:172.30.249.217:443: deleting (22 remain)
  61.5  19 | c : SW#17:10.100.102.3:32994: uwrite: got EPIPE
  61.6 TEL | (proxy checking local liveness)
  61.6  12 | 2018-11-05T15:10:04+0000 [Poll#info] Checkpoint
  61.7  12 | 2018-11-05T15:10:04+0000 [-] DNSDatagramProtocol starting on 49898
  61.7  12 | 2018-11-05T15:10:04+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e9e8>
  61.7  12 | 2018-11-05T15:10:04+0000 [-] (UDP Port 14547 Closed)
  61.7  12 | 2018-11-05T15:10:04+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ada90>
  61.8  12 | 2018-11-05T15:10:05+0000 [-] DNSDatagramProtocol starting on 25749
  61.8  12 | 2018-11-05T15:10:05+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672d2c18>
  61.8  12 | 2018-11-05T15:10:05+0000 [-] (UDP Port 42972 Closed)
  61.8  12 | 2018-11-05T15:10:05+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ad978>
  61.8  12 | 2018-11-05T15:10:05+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  61.8  12 | 2018-11-05T15:10:05+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  61.8  12 | 2018-11-05T15:10:05+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
  62.5  19 | c : DNS request from ('10.100.102.3', 52031) to None: 57 bytes
  62.5  12 | 2018-11-05T15:10:05+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  62.7  12 | 2018-11-05T15:10:05+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  62.7  12 | 2018-11-05T15:10:05+0000 [stdout#info] Failed to lookup b'api.mixpanel.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  62.7  12 | 2018-11-05T15:10:05+0000 [stdout#info] ], falling back to b'api.mixpanel.com.localdomain'
  62.7  12 | 2018-11-05T15:10:05+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  62.7  12 | 2018-11-05T15:10:05+0000 [stdout#info] Failed to lookup b'www.msftconnecttest.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  62.7  12 | 2018-11-05T15:10:05+0000 [stdout#info] ], falling back to b'www.msftconnecttest.com.localdomain'
  63.6  12 | 2018-11-05T15:10:06+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  63.6  19 | c : DNS request from ('10.100.102.3', 43114) to None: 53 bytes
  63.6  12 | 2018-11-05T15:10:06+0000 [stdout#info] Updated query of type 1 from b'www.msftconnecttest.com.localdomain' to b'www.msftconnecttest.com'
  63.6  12 | 2018-11-05T15:10:06+0000 [stdout#info] A query: b'www.msftconnecttest.com'
  63.7  12 | 2018-11-05T15:10:06+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  63.7  12 | 2018-11-05T15:10:06+0000 [stdout#info] Failed to lookup b'www.msftconnecttest.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  63.7  12 | 2018-11-05T15:10:06+0000 [stdout#info] ], falling back to b'www.msftconnecttest.com.localdomain'
  64.4  12 | 2018-11-05T15:10:07+0000 [-] DNSDatagramProtocol starting on 26867
  64.4  12 | 2018-11-05T15:10:07+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729de48>
  64.4  12 | 2018-11-05T15:10:07+0000 [-] (UDP Port 43024 Closed)
  64.4  12 | 2018-11-05T15:10:07+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ad358>
  64.5  12 | 2018-11-05T15:10:07+0000 [-] DNSDatagramProtocol starting on 36349
  64.5  12 | 2018-11-05T15:10:07+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ad390>
  64.5  12 | 2018-11-05T15:10:07+0000 [-] (UDP Port 1689 Closed)
  64.5  12 | 2018-11-05T15:10:07+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672ab160>
  64.6  12 | 2018-11-05T15:10:07+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  64.6  12 | 2018-11-05T15:10:07+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  64.6  12 | 2018-11-05T15:10:07+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  67.5  19 | c : DNS request from ('10.100.102.3', 52031) to None: 57 bytes
  67.5  12 | 2018-11-05T15:10:10+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  67.5  19 | c : DNS request from ('10.100.102.3', 33822) to None: 69 bytes
  67.5  12 | 2018-11-05T15:10:10+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  67.5  12 | 2018-11-05T15:10:10+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  67.5  12 | 2018-11-05T15:10:10+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  68.5  19 | c : DNS request from ('10.100.102.3', 38539) to None: 57 bytes
  68.5  12 | 2018-11-05T15:10:11+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  68.6  12 | 2018-11-05T15:10:11+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  68.6  12 | 2018-11-05T15:10:11+0000 [stdout#info] Failed to lookup b'www.msftconnecttest.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  68.6  12 | 2018-11-05T15:10:11+0000 [stdout#info] ], falling back to b'www.msftconnecttest.com.localdomain'
  72.5  12 | 2018-11-05T15:10:15+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  72.5  19 | c : DNS request from ('10.100.102.3', 33822) to None: 69 bytes
  72.5  12 | 2018-11-05T15:10:15+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  72.5  12 | 2018-11-05T15:10:15+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  72.5  12 | 2018-11-05T15:10:15+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  72.5  12 | 2018-11-05T15:10:15+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  72.5  12 | 2018-11-05T15:10:15+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  72.6  19 | c : DNS request from ('10.100.102.3', 37193) to None: 39 bytes
  72.6  12 | 2018-11-05T15:10:15+0000 [stdout#info] A query: b'plugins.jetbrains.com'
  72.7  12 | 2018-11-05T15:10:15+0000 [-] DNSDatagramProtocol starting on 50560
  72.7  12 | 2018-11-05T15:10:15+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bbb70>
  72.7  12 | 2018-11-05T15:10:15+0000 [-] (UDP Port 49898 Closed)
  72.7  12 | 2018-11-05T15:10:15+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e9e8>
  72.8  12 | 2018-11-05T15:10:16+0000 [-] DNSDatagramProtocol starting on 14452
  72.8  12 | 2018-11-05T15:10:16+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729df60>
  72.8  12 | 2018-11-05T15:10:16+0000 [-] (UDP Port 25749 Closed)
  72.8  12 | 2018-11-05T15:10:16+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672d2c18>
  73.5  19 | c : DNS request from ('10.100.102.3', 38539) to None: 57 bytes
  73.5  12 | 2018-11-05T15:10:16+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  73.5  19 | c : DNS request from ('10.100.102.3', 40647) to None: 69 bytes
  73.5  19 | c : SW#10:10.100.102.3:32988: deleting (23 remain)
  73.5  19 | c : SW#10:10.100.102.3:32988: error was: uread: [Errno 104] Connection reset by peer
  73.5  19 | c : SW'unknown':Mux#86: deleting (22 remain)
  73.5  19 | c : SW#17:10.100.102.3:32994: deleting (21 remain)
  73.5  19 | c : SW#17:10.100.102.3:32994: error was: nowrite: [Errno 107] Transport endpoint is not connected
  73.5  19 | c : SW'unknown':Mux#87: deleting (20 remain)
  73.5  12 | 2018-11-05T15:10:16+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  73.5  12 | 2018-11-05T15:10:16+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  73.5  12 | 2018-11-05T15:10:16+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  76.9  12 | 2018-11-05T15:10:20+0000 [-] Unhandled Error
  76.9  12 | 	Traceback (most recent call last):
  76.9  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 1, 1)]
  76.9  12 | 
  76.9  12 | 2018-11-05T15:10:20+0000 [-] Unhandled Error
  76.9  12 | 	Traceback (most recent call last):
  76.9  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 1, 1)]
  76.9  12 | 
  76.9  12 | 2018-11-05T15:10:20+0000 [-] (UDP Port 19735 Closed)
  76.9  12 | 2018-11-05T15:10:20+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354668>
  77.0  12 | 2018-11-05T15:10:20+0000 [-] Unhandled Error
  77.0  12 | 	Traceback (most recent call last):
  77.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 28, 1)]
  77.0  12 | 
  77.0  12 | 2018-11-05T15:10:20+0000 [-] Unhandled Error
  77.0  12 | 	Traceback (most recent call last):
  77.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 28, 1)]
  77.0  12 | 
  77.0  12 | 2018-11-05T15:10:20+0000 [-] (UDP Port 52278 Closed)
  77.0  12 | 2018-11-05T15:10:20+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672e58d0>
  77.5  19 | c : DNS request from ('10.100.102.3', 57165) to None: 49 bytes
  77.5  12 | 2018-11-05T15:10:20+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  77.5  12 | 2018-11-05T15:10:20+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  77.5  12 | 2018-11-05T15:10:20+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  77.5  12 | 2018-11-05T15:10:20+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  77.6  19 | c : DNS request from ('10.100.102.3', 37193) to None: 39 bytes
  77.6  19 | c : DNS request from ('10.100.102.3', 54727) to None: 51 bytes
  77.6  12 | 2018-11-05T15:10:20+0000 [stdout#info] A query: b'plugins.jetbrains.com'
  77.6  12 | 2018-11-05T15:10:20+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  77.7  12 | 2018-11-05T15:10:20+0000 [stdout#info] Updated query of type 1 from b'plugins.jetbrains.com.localdomain' to b'plugins.jetbrains.com'
  77.7  12 | 2018-11-05T15:10:20+0000 [stdout#info] A query: b'plugins.jetbrains.com'
  78.5  19 | c : DNS request from ('10.100.102.3', 40647) to None: 69 bytes
  78.5  12 | 2018-11-05T15:10:21+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  78.5  12 | 2018-11-05T15:10:21+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  78.5  12 | 2018-11-05T15:10:21+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  78.5  12 | 2018-11-05T15:10:21+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  78.5  12 | 2018-11-05T15:10:21+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  78.5  12 | 2018-11-05T15:10:21+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  81.5  19 | c : DNS request from ('10.100.102.3', 34923) to None: 37 bytes
  81.5  19 | c : DNS request from ('10.100.102.3', 34923) to None: 37 bytes
  81.5  12 | 2018-11-05T15:10:24+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  81.5  12 | 2018-11-05T15:10:24+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
  81.5  12 | 2018-11-05T15:10:24+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  82.5  19 | c : DNS request from ('10.100.102.3', 57165) to None: 49 bytes
  82.5  12 | 2018-11-05T15:10:25+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  82.5  19 | c : DNS request from ('10.100.102.3', 57764) to None: 61 bytes
  82.5  12 | 2018-11-05T15:10:25+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  82.6  12 | 2018-11-05T15:10:25+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
  82.6  12 | 2018-11-05T15:10:25+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  82.6  12 | 2018-11-05T15:10:25+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  82.6  19 | c : DNS request from ('10.100.102.3', 54727) to None: 51 bytes
  82.6  12 | 2018-11-05T15:10:25+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  82.6  12 | 2018-11-05T15:10:25+0000 [stdout#info] Failed to lookup b'plugins.jetbrains.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  82.6  12 | 2018-11-05T15:10:25+0000 [stdout#info] ], falling back to b'plugins.jetbrains.com.localdomain'
  82.7  12 | 2018-11-05T15:10:25+0000 [-] DNSDatagramProtocol starting on 2984
  82.7  12 | 2018-11-05T15:10:25+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bbfd0>
  82.7  12 | 2018-11-05T15:10:25+0000 [stdout#info] Updated query of type 1 from b'plugins.jetbrains.com.localdomain' to b'plugins.jetbrains.com'
  82.7  12 | 2018-11-05T15:10:25+0000 [stdout#info] A query: b'plugins.jetbrains.com'
  83.5  19 | c : DNS request from ('10.100.102.3', 37861) to None: 49 bytes
  83.5  12 | 2018-11-05T15:10:26+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  83.5  12 | 2018-11-05T15:10:26+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  83.5  12 | 2018-11-05T15:10:26+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  83.5  12 | 2018-11-05T15:10:26+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  83.7  12 | 2018-11-05T15:10:26+0000 [-] DNSDatagramProtocol starting on 16621
  83.7  12 | 2018-11-05T15:10:26+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354ac8>
  83.7  12 | 2018-11-05T15:10:26+0000 [-] (UDP Port 2984 Closed)
  83.7  12 | 2018-11-05T15:10:26+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bbfd0>
  86.5  19 | c : DNS request from ('10.100.102.3', 34923) to None: 37 bytes
  86.5  19 | c : DNS request from ('10.100.102.3', 34923) to None: 37 bytes
  86.5  12 | 2018-11-05T15:10:29+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  86.5  12 | 2018-11-05T15:10:29+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
  86.5  12 | 2018-11-05T15:10:29+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  86.5  12 | 2018-11-05T15:10:29+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  86.5  12 | 2018-11-05T15:10:29+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  86.6  19 | c : DNS request from ('10.100.102.3', 38620) to None: 49 bytes
  86.6  19 | c : DNS request from ('10.100.102.3', 38620) to None: 49 bytes
  86.6  12 | 2018-11-05T15:10:29+0000 [stdout#info] Updated query of type 1 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  86.6  12 | 2018-11-05T15:10:29+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  86.6  12 | 2018-11-05T15:10:29+0000 [stdout#info] Updated query of type 28 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  86.6  12 | 2018-11-05T15:10:29+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
  86.7  12 | 2018-11-05T15:10:29+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  86.7  12 | 2018-11-05T15:10:29+0000 [-] DNSDatagramProtocol starting on 27543
  86.7  12 | 2018-11-05T15:10:29+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dda20>
  86.7  12 | 2018-11-05T15:10:29+0000 [-] (UDP Port 16621 Closed)
  86.7  12 | 2018-11-05T15:10:29+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867354ac8>
  87.5  19 | c : DNS request from ('10.100.102.3', 51417) to None: 57 bytes
  87.5  12 | 2018-11-05T15:10:30+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  87.5  19 | c : DNS request from ('10.100.102.3', 57764) to None: 61 bytes
  87.5  12 | 2018-11-05T15:10:30+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
  87.5  12 | 2018-11-05T15:10:30+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  87.6  12 | 2018-11-05T15:10:30+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  87.6  12 | 2018-11-05T15:10:30+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  87.6  12 | 2018-11-05T15:10:30+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  87.6  12 | 2018-11-05T15:10:30+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
  87.6  12 | 2018-11-05T15:10:30+0000 [-] DNSDatagramProtocol starting on 22795
  87.6  12 | 2018-11-05T15:10:30+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86733c400>
  87.7  12 | 2018-11-05T15:10:30+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  87.7  12 | 2018-11-05T15:10:30+0000 [stdout#info] Failed to lookup b'plugins.jetbrains.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  87.7  12 | 2018-11-05T15:10:30+0000 [stdout#info] ], falling back to b'plugins.jetbrains.com.localdomain'
  88.5  19 | c : DNS request from ('10.100.102.3', 37861) to None: 49 bytes
  88.5  12 | 2018-11-05T15:10:31+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  88.5  12 | 2018-11-05T15:10:31+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  88.5  19 | c : DNS request from ('10.100.102.3', 42774) to None: 61 bytes
  88.5  12 | 2018-11-05T15:10:31+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
  88.5  12 | 2018-11-05T15:10:31+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  88.6  12 | 2018-11-05T15:10:31+0000 [-] DNSDatagramProtocol starting on 54882
  88.6  12 | 2018-11-05T15:10:31+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dde80>
  88.6  12 | 2018-11-05T15:10:31+0000 [-] (UDP Port 22795 Closed)
  88.6  12 | 2018-11-05T15:10:31+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86733c400>
  89.9  19 | c : Accept TCP: 10.100.102.3:33376 -> 172.30.249.217:443.
  89.9  19 | c : Accept TCP: 10.100.102.3:33382 -> 172.30.249.217:443.
  89.9  19 | c : Accept TCP: 10.100.102.3:33384 -> 172.30.249.217:443.
  89.9  19 | c : Accept TCP: 10.100.102.3:33390 -> 172.30.249.217:443.
  90.0  19 |  s: SW'unknown':Mux#85: deleting (23 remain)
  90.0  19 |  s: SW#14:172.30.249.217:443: deleting (22 remain)
  90.0  19 |  s: SW'unknown':Mux#82: deleting (21 remain)
  90.0  19 |  s: SW#11:172.30.249.217:443: deleting (20 remain)
  90.0  19 |  s: SW'unknown':Mux#84: deleting (19 remain)
  90.0  19 |  s: SW#13:172.30.249.217:443: deleting (18 remain)
  90.0  19 |  s: SW'unknown':Mux#86: deleting (17 remain)
  90.0  19 |  s: SW#6:172.30.249.217:443: deleting (16 remain)
  90.0  19 | c : Accept TCP: 10.100.102.3:33400 -> 172.30.249.217:443.
  90.1  19 | c : SW'unknown':Mux#77: deleting (29 remain)
  90.1  19 | c : SW#12:10.100.102.3:32912: deleting (28 remain)
  90.1  19 | c : SW#12:10.100.102.3:32912: error was: nowrite: [Errno 107] Transport endpoint is not connected
  90.1  19 | c : SW#16:10.100.102.3:32924: deleting (27 remain)
  90.1  19 | c : SW#16:10.100.102.3:32924: error was: nowrite: [Errno 107] Transport endpoint is not connected
  90.1  19 | c : SW'unknown':Mux#78: deleting (26 remain)
  90.1  19 | c : SW#15:10.100.102.3:32922: deleting (25 remain)
  90.1  19 | c : SW#15:10.100.102.3:32922: error was: uread: [Errno 104] Connection reset by peer
  90.1  19 | c : SW'unknown':Mux#79: deleting (24 remain)
  90.1  19 | c : SW'unknown':Mux#81: deleting (23 remain)
  90.1  19 | c : SW#18:10.100.102.3:32940: deleting (22 remain)
  90.1  19 | c : SW#18:10.100.102.3:32940: error was: uread: [Errno 104] Connection reset by peer
  90.1  19 | c : SW'unknown':Mux#84: deleting (21 remain)
  90.1  19 | c : SW#21:10.100.102.3:32962: deleting (20 remain)
  90.1  19 | c : SW#21:10.100.102.3:32962: error was: uread: [Errno 104] Connection reset by peer
  90.1  19 | c : SW'unknown':Mux#85: deleting (19 remain)
  90.1  19 | c : SW#22:10.100.102.3:32972: deleting (18 remain)
  90.1  19 | c : SW#22:10.100.102.3:32972: error was: uread: [Errno 104] Connection reset by peer
  90.1  19 | c : SW'unknown':Mux#27: deleting (17 remain)
  90.1  19 | c : SW#13:10.100.102.3:60762: deleting (16 remain)
  90.1  19 | c : SW#13:10.100.102.3:60762: error was: uread: [Errno 104] Connection reset by peer
  90.1  19 | c : Accept TCP: 10.100.102.3:33406 -> 172.30.249.217:443.
  90.1  19 |  s: SW'unknown':Mux#18: deleting (23 remain)
  90.1  19 |  s: SW#18:172.30.249.217:443: deleting (22 remain)
  90.1  19 | c : Accept TCP: 10.100.102.3:33408 -> 172.30.249.217:443.
  90.1  19 | c : Accept TCP: 10.100.102.3:33410 -> 172.30.249.217:443.
  90.1  19 | c : SW#10:10.100.102.3:33376: deleting (21 remain)
  90.1  19 | c : SW#10:10.100.102.3:33376: error was: uread: [Errno 104] Connection reset by peer
  90.1  19 | c : SW'unknown':Mux#115: deleting (20 remain)
  90.1  19 | c : SW#19:10.100.102.3:33384: deleting (19 remain)
  90.1  19 | c : SW#19:10.100.102.3:33384: error was: uread: [Errno 104] Connection reset by peer
  90.1  19 | c : SW'unknown':Mux#117: deleting (18 remain)
  90.2  19 |  s: SW'unknown':Mux#20: deleting (21 remain)
  90.2  19 |  s: SW#8:172.30.249.217:443: deleting (20 remain)
  90.2  19 |  s: SW#15:172.30.249.217:443: deleting (19 remain)
  90.2  19 |  s: SW'unknown':Mux#25: deleting (18 remain)
  90.2  19 |  s: SW'unknown':Mux#28: deleting (17 remain)
  90.2  19 |  s: SW#23:172.30.249.217:443: deleting (16 remain)
  90.2  19 |  s: SW'unknown':Mux#83: deleting (15 remain)
  90.2  19 |  s: SW#12:172.30.249.217:443: deleting (14 remain)
  90.2  19 |  s: SW'unknown':Mux#87: deleting (13 remain)
  90.2  19 |  s: SW#16:172.30.249.217:443: deleting (12 remain)
  90.2  19 | c : SW#17:10.100.102.3:33382: uwrite: got EPIPE
  90.2  19 | c : warning: closed channel 116 got cmd=TCP_EOF len=0
  90.2  19 |  s: warning: closed channel 116 got cmd=TCP_STOP_SENDING len=0
  90.2  19 | c : Accept TCP: 10.100.102.3:33424 -> 172.30.249.217:443.
  90.2  19 | c : Accept TCP: 10.100.102.3:33426 -> 172.30.249.217:443.
  90.2  19 | c : SW#20:10.100.102.3:33390: uwrite: got EPIPE
  90.3  19 | c : SW#17:10.100.102.3:33382: deleting (21 remain)
  90.3  19 | c : SW#17:10.100.102.3:33382: error was: nowrite: [Errno 107] Transport endpoint is not connected
  90.3  19 | c : SW'unknown':Mux#116: deleting (20 remain)
  90.3  19 | c : SW#23:10.100.102.3:33400: deleting (19 remain)
  90.3  19 | c : SW#23:10.100.102.3:33400: error was: uread: [Errno 104] Connection reset by peer
  90.3  19 | c : SW'unknown':Mux#119: deleting (18 remain)
  90.3  19 | c : SW#20:10.100.102.3:33390: deleting (17 remain)
  90.3  19 | c : SW#20:10.100.102.3:33390: error was: nowrite: [Errno 107] Transport endpoint is not connected
  90.3  19 | c : SW'unknown':Mux#118: deleting (16 remain)
  90.4  19 |  s: SW'unknown':Mux#115: deleting (21 remain)
  90.4  19 |  s: SW#54:172.30.249.217:443: deleting (20 remain)
  90.4  19 |  s: SW'unknown':Mux#116: deleting (19 remain)
  90.4  19 |  s: SW#6:172.30.249.217:443: deleting (18 remain)
  90.4  19 |  s: SW'unknown':Mux#117: deleting (17 remain)
  90.4  19 |  s: SW#7:172.30.249.217:443: deleting (16 remain)
  90.4  19 |  s: SW'unknown':Mux#118: deleting (15 remain)
  90.4  19 |  s: SW#11:172.30.249.217:443: deleting (14 remain)
  90.4  19 |  s: SW'unknown':Mux#119: deleting (13 remain)
  90.4  19 |  s: SW#13:172.30.249.217:443: deleting (12 remain)
  90.6  19 | c : Accept TCP: 10.100.102.3:33444 -> 172.30.249.217:443.
  90.6  19 | c : Accept TCP: 10.100.102.3:33446 -> 172.30.249.217:443.
  90.7  19 | c : SW#12:10.100.102.3:33406: uwrite: got EPIPE
  90.8  19 |  s: warning: closed channel 120 got cmd=TCP_STOP_SENDING len=0
  90.8  19 | c : warning: closed channel 120 got cmd=TCP_EOF len=0
  90.8  19 | c : SW#10:10.100.102.3:33424: uwrite: got EPIPE
  90.8  19 | c : warning: closed channel 123 got cmd=TCP_EOF len=0
  90.8  19 | c : SW#13:10.100.102.3:33408: uwrite: got EPIPE
  90.8  19 | c : SW#15:10.100.102.3:33410: uwrite: got EPIPE
  90.8  19 |  s: SW'unknown':Mux#120: deleting (15 remain)
  90.8  19 |  s: SW#8:172.30.249.217:443: deleting (14 remain)
  90.8  19 |  s: SW'unknown':Mux#121: deleting (13 remain)
  90.8  19 |  s: SW#12:172.30.249.217:443: deleting (12 remain)
  90.8 TEL | [33] Running: sudo -n echo -n
  90.9  19 |  s: SW'unknown':Mux#122: deleting (11 remain)
  90.9  19 |  s: SW#14:172.30.249.217:443: deleting (10 remain)
  90.9  19 |  s: warning: closed channel 123 got cmd=TCP_STOP_SENDING len=0
  90.9  19 |  s: warning: closed channel 122 got cmd=TCP_STOP_SENDING len=0
  90.9  19 | c : warning: closed channel 122 got cmd=TCP_EOF len=0
  91.0  19 | c : SW#16:10.100.102.3:33426: uwrite: got EPIPE
  91.0  19 | c : SW#12:10.100.102.3:33406: deleting (19 remain)
  91.0  19 | c : SW#12:10.100.102.3:33406: error was: nowrite: [Errno 107] Transport endpoint is not connected
  91.0  19 | c : SW'unknown':Mux#120: deleting (18 remain)
  91.0  19 | c : SW#10:10.100.102.3:33424: deleting (17 remain)
  91.0  19 | c : SW#10:10.100.102.3:33424: error was: nowrite: [Errno 107] Transport endpoint is not connected
  91.0  19 | c : SW'unknown':Mux#123: deleting (16 remain)
  91.0  19 | c : SW#13:10.100.102.3:33408: deleting (15 remain)
  91.0  19 | c : SW#13:10.100.102.3:33408: error was: nowrite: [Errno 107] Transport endpoint is not connected
  91.0  19 | c : SW'unknown':Mux#121: deleting (14 remain)
  91.0  19 | c : SW#15:10.100.102.3:33410: deleting (13 remain)
  91.0  19 | c : SW#15:10.100.102.3:33410: error was: nowrite: [Errno 107] Transport endpoint is not connected
  91.0  19 | c : SW'unknown':Mux#122: deleting (12 remain)
  91.1  19 | c : SW#17:10.100.102.3:33444: uwrite: got EPIPE
  91.2  19 | c : warning: closed channel 125 got cmd=TCP_EOF len=0
  91.2  19 |  s: warning: closed channel 125 got cmd=TCP_STOP_SENDING len=0
  91.2  19 | c : warning: closed channel 126 got cmd=TCP_DATA len=31
  91.2  19 | c : warning: closed channel 126 got cmd=TCP_EOF len=0
  91.2  19 |  s: warning: closed channel 126 got cmd=TCP_STOP_SENDING len=0
  91.5  12 | 2018-11-05T15:10:34+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  91.5  12 | 2018-11-05T15:10:34+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  91.6  19 | c : DNS request from ('10.100.102.3', 38620) to None: 49 bytes
  91.6  19 | c : DNS request from ('10.100.102.3', 38620) to None: 49 bytes
  91.6 TEL | (proxy checking local liveness)
  91.6  12 | 2018-11-05T15:10:34+0000 [stdout#info] Updated query of type 1 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  91.6  12 | 2018-11-05T15:10:34+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  91.6  12 | 2018-11-05T15:10:34+0000 [Poll#info] Checkpoint
  91.6  12 | 2018-11-05T15:10:34+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  91.6  12 | 2018-11-05T15:10:34+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  91.6  12 | 2018-11-05T15:10:34+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  91.6  12 | 2018-11-05T15:10:34+0000 [-] DNSDatagramProtocol starting on 63168
  91.6  12 | 2018-11-05T15:10:34+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672d2c18>
  91.6  12 | 2018-11-05T15:10:34+0000 [-] DNSDatagramProtocol starting on 15664
  91.6  12 | 2018-11-05T15:10:34+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bb5f8>
  91.6  12 | 2018-11-05T15:10:34+0000 [-] (UDP Port 54882 Closed)
  91.6  12 | 2018-11-05T15:10:34+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dde80>
  91.7  12 | 2018-11-05T15:10:34+0000 [stdout#info] Updated query of type 28 from b'cups.tlv.redhat.com.localdomain' to b'cups.tlv.redhat.com'
  91.7  12 | 2018-11-05T15:10:34+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
  91.7  12 | 2018-11-05T15:10:34+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
  91.7  12 | 2018-11-05T15:10:34+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  91.7  12 | 2018-11-05T15:10:34+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  91.7  12 | 2018-11-05T15:10:34+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  91.8  12 | 2018-11-05T15:10:34+0000 [-] DNSDatagramProtocol starting on 61175
  91.8  12 | 2018-11-05T15:10:35+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6908>
  92.5  19 | c : DNS request from ('10.100.102.3', 51417) to None: 57 bytes
  92.5  12 | 2018-11-05T15:10:35+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  92.5  12 | 2018-11-05T15:10:35+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  92.6  19 | c : DNS request from ('10.100.102.3', 54086) to None: 69 bytes
  92.6  12 | 2018-11-05T15:10:35+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  92.6  12 | 2018-11-05T15:10:35+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  92.6  12 | 2018-11-05T15:10:35+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
  92.6  12 | 2018-11-05T15:10:35+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  92.6  12 | 2018-11-05T15:10:35+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  92.7  12 | 2018-11-05T15:10:35+0000 [-] DNSDatagramProtocol starting on 10916
  92.7  12 | 2018-11-05T15:10:35+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6d68>
  92.7  12 | 2018-11-05T15:10:35+0000 [-] (UDP Port 63168 Closed)
  92.7  12 | 2018-11-05T15:10:35+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672d2c18>
  92.8  12 | 2018-11-05T15:10:36+0000 [-] DNSDatagramProtocol starting on 31593
  92.8  12 | 2018-11-05T15:10:36+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6d30>
  92.8  12 | 2018-11-05T15:10:36+0000 [-] (UDP Port 61175 Closed)
  92.8  12 | 2018-11-05T15:10:36+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6908>
  93.5  19 | c : DNS request from ('10.100.102.3', 58664) to None: 57 bytes
  93.5  12 | 2018-11-05T15:10:36+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  93.5  12 | 2018-11-05T15:10:36+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  93.5  19 | c : DNS request from ('10.100.102.3', 42774) to None: 61 bytes
  93.5  12 | 2018-11-05T15:10:36+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
  93.5  12 | 2018-11-05T15:10:36+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  93.5  12 | 2018-11-05T15:10:36+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  93.5  12 | 2018-11-05T15:10:36+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  93.5  12 | 2018-11-05T15:10:36+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
  95.5  19 | c : DNS request from ('10.100.102.3', 41126) to None: 49 bytes
  95.5  12 | 2018-11-05T15:10:38+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
  95.7  12 | 2018-11-05T15:10:38+0000 [-] DNSDatagramProtocol starting on 24098
  95.7  12 | 2018-11-05T15:10:38+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671c7f98>
  95.7  12 | 2018-11-05T15:10:38+0000 [-] (UDP Port 10916 Closed)
  95.7  12 | 2018-11-05T15:10:38+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6d68>
  95.8  12 | 2018-11-05T15:10:39+0000 [-] DNSDatagramProtocol starting on 64937
  95.8  12 | 2018-11-05T15:10:39+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671c7080>
  95.8  12 | 2018-11-05T15:10:39+0000 [-] (UDP Port 31593 Closed)
  95.8  12 | 2018-11-05T15:10:39+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6d30>
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Unhandled Error
  96.0  12 | 	Traceback (most recent call last):
  96.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('clients4.google.com.localdomain', 1, 1)]
  96.0  12 | 
  96.0  12 | 2018-11-05T15:10:39+0000 [-] (UDP Port 22971 Closed)
  96.0  12 | 2018-11-05T15:10:39+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e6a0>
  96.6  12 | 2018-11-05T15:10:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  96.6  12 | 2018-11-05T15:10:39+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  96.6  12 | 2018-11-05T15:10:39+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  96.7  12 | 2018-11-05T15:10:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  96.7  12 | 2018-11-05T15:10:39+0000 [stdout#info] Failed to lookup b'cups.tlv.redhat.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  96.7  12 | 2018-11-05T15:10:39+0000 [stdout#info] ], falling back to b'cups.tlv.redhat.com.localdomain'
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Unhandled Error
  97.0  12 | 	Traceback (most recent call last):
  97.0  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('db5-client-s.gateway.messenger.live.com.localdomain', 1, 1)]
  97.0  12 | 
  97.0  12 | 2018-11-05T15:10:40+0000 [-] (UDP Port 50155 Closed)
  97.0  12 | 2018-11-05T15:10:40+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672ab828>
  97.6  12 | 2018-11-05T15:10:40+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  97.6  19 | c : DNS request from ('10.100.102.3', 54086) to None: 69 bytes
  97.6  12 | 2018-11-05T15:10:40+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  97.6  12 | 2018-11-05T15:10:40+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  97.7  12 | 2018-11-05T15:10:40+0000 [-] DNSDatagramProtocol starting on 59761
  97.7  12 | 2018-11-05T15:10:40+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bbba8>
  97.7  12 | 2018-11-05T15:10:40+0000 [-] (UDP Port 27543 Closed)
  97.7  12 | 2018-11-05T15:10:40+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dda20>
  97.7  12 | 2018-11-05T15:10:40+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  97.7  12 | 2018-11-05T15:10:40+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  97.7  12 | 2018-11-05T15:10:40+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
  97.7  12 | 2018-11-05T15:10:40+0000 [-] DNSDatagramProtocol starting on 13745
  97.7  12 | 2018-11-05T15:10:40+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dd160>
  98.5  19 | c : DNS request from ('10.100.102.3', 58664) to None: 57 bytes
  98.5  12 | 2018-11-05T15:10:41+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  98.5  19 | c : DNS request from ('10.100.102.3', 37560) to None: 69 bytes
  98.5  12 | 2018-11-05T15:10:41+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  98.5  12 | 2018-11-05T15:10:41+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
  98.6  12 | 2018-11-05T15:10:41+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
  98.6  12 | 2018-11-05T15:10:41+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
  98.6  12 | 2018-11-05T15:10:41+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
  98.6  12 | 2018-11-05T15:10:41+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
  98.7  12 | 2018-11-05T15:10:41+0000 [-] DNSDatagramProtocol starting on 42033
  98.7  12 | 2018-11-05T15:10:41+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dd978>
  98.7  12 | 2018-11-05T15:10:41+0000 [-] (UDP Port 13745 Closed)
  98.7  12 | 2018-11-05T15:10:41+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dd160>
 100.5  19 | c : DNS request from ('10.100.102.3', 57134) to None: 35 bytes
 100.5  12 | 2018-11-05T15:10:43+0000 [stdout#info] A query: b'0.docs.google.com'
 100.5  19 | c : DNS request from ('10.100.102.3', 41126) to None: 49 bytes
 100.5  12 | 2018-11-05T15:10:43+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 100.5  19 | c : DNS request from ('10.100.102.3', 48247) to None: 61 bytes
 100.5  12 | 2018-11-05T15:10:43+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 100.5  12 | 2018-11-05T15:10:43+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 100.5  12 | 2018-11-05T15:10:43+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 100.7  19 | c : DNS request from ('10.100.102.3', 58795) to None: 37 bytes
 100.7  12 | 2018-11-05T15:10:44+0000 [stdout#info] A query: b'clients4.google.com'
 101.5  19 | c : DNS request from ('10.100.102.3', 48744) to None: 49 bytes
 101.5  12 | 2018-11-05T15:10:44+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 101.5  19 |  s: SW'unknown':Mux#125: deleting (9 remain)
 101.5  19 |  s: SW#6:172.30.249.217:443: deleting (8 remain)
 101.5  19 |  s: SW'unknown':Mux#126: deleting (7 remain)
 101.5  19 |  s: SW#7:172.30.249.217:443: deleting (6 remain)
 101.7  12 | 2018-11-05T15:10:44+0000 [-] DNSDatagramProtocol starting on 20580
 101.7  12 | 2018-11-05T15:10:44+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729d748>
 101.7  12 | 2018-11-05T15:10:44+0000 [-] (UDP Port 42033 Closed)
 101.7  12 | 2018-11-05T15:10:44+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dd978>
 102.6  12 | 2018-11-05T15:10:45+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 102.6  12 | 2018-11-05T15:10:45+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 102.6  12 | 2018-11-05T15:10:45+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
 102.6  12 | 2018-11-05T15:10:45+0000 [-] DNSDatagramProtocol starting on 63019
 102.6  12 | 2018-11-05T15:10:45+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dd978>
 102.6  12 | 2018-11-05T15:10:45+0000 [-] (UDP Port 15664 Closed)
 102.6  12 | 2018-11-05T15:10:45+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bb5f8>
 103.5  19 | c : DNS request from ('10.100.102.3', 37560) to None: 69 bytes
 103.5  12 | 2018-11-05T15:10:46+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
 103.5  12 | 2018-11-05T15:10:46+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 103.6  12 | 2018-11-05T15:10:46+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 103.6  12 | 2018-11-05T15:10:46+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 103.6  12 | 2018-11-05T15:10:46+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 103.6  12 | 2018-11-05T15:10:46+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
 105.5  19 | c : DNS request from ('10.100.102.3', 57134) to None: 35 bytes
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] A query: b'0.docs.google.com'
 105.5  19 | c : DNS request from ('10.100.102.3', 47443) to None: 47 bytes
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] A query: b'0.docs.google.com'
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 105.5  19 | c : DNS request from ('10.100.102.3', 48247) to None: 61 bytes
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 105.5  12 | 2018-11-05T15:10:48+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 105.6  12 | 2018-11-05T15:10:48+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 105.6  12 | 2018-11-05T15:10:48+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 105.7  19 | c : DNS request from ('10.100.102.3', 58795) to None: 37 bytes
 105.7  12 | 2018-11-05T15:10:49+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 105.7  19 | c : DNS request from ('10.100.102.3', 41087) to None: 49 bytes
 105.7  19 | c : SW#16:10.100.102.3:33426: deleting (11 remain)
 105.7  19 | c : SW#16:10.100.102.3:33426: error was: nowrite: [Errno 107] Transport endpoint is not connected
 105.7  19 | c : SW'unknown':Mux#124: deleting (10 remain)
 105.7  19 | c : SW#17:10.100.102.3:33444: deleting (9 remain)
 105.7  19 | c : SW#17:10.100.102.3:33444: error was: nowrite: [Errno 107] Transport endpoint is not connected
 105.7  19 | c : SW'unknown':Mux#125: deleting (8 remain)
 105.7  19 | c : SW#18:10.100.102.3:33446: deleting (7 remain)
 105.7  19 | c : SW#18:10.100.102.3:33446: error was: uread: [Errno 104] Connection reset by peer
 105.7  19 | c : SW'unknown':Mux#126: deleting (6 remain)
 105.7  12 | 2018-11-05T15:10:49+0000 [stdout#info] A query: b'clients4.google.com'
 105.7  12 | 2018-11-05T15:10:49+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 105.8  12 | 2018-11-05T15:10:49+0000 [stdout#info] A query: b'clients4.google.com'
 106.5  19 | c : DNS request from ('10.100.102.3', 59451) to None: 35 bytes
 106.5  12 | 2018-11-05T15:10:49+0000 [stdout#info] A query: b'0.docs.google.com'
 106.5  19 | c : DNS request from ('10.100.102.3', 48744) to None: 49 bytes
 106.5  12 | 2018-11-05T15:10:49+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 106.5  12 | 2018-11-05T15:10:49+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 106.5  19 | c : DNS request from ('10.100.102.3', 39515) to None: 61 bytes
 106.5  12 | 2018-11-05T15:10:49+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 106.5  12 | 2018-11-05T15:10:49+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 106.7  12 | 2018-11-05T15:10:49+0000 [-] DNSDatagramProtocol starting on 33935
 106.7  12 | 2018-11-05T15:10:49+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672769b0>
 106.7  12 | 2018-11-05T15:10:49+0000 [-] (UDP Port 24098 Closed)
 106.7  12 | 2018-11-05T15:10:49+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671c7f98>
 106.7  19 | c : DNS request from ('10.100.102.3', 56011) to None: 37 bytes
 106.7  12 | 2018-11-05T15:10:50+0000 [stdout#info] A query: b'clients4.google.com'
 106.8  12 | 2018-11-05T15:10:50+0000 [-] DNSDatagramProtocol starting on 59239
 106.8  12 | 2018-11-05T15:10:50+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672767b8>
 106.8  12 | 2018-11-05T15:10:50+0000 [-] (UDP Port 64937 Closed)
 106.8  12 | 2018-11-05T15:10:50+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671c7080>
 108.5  12 | 2018-11-05T15:10:51+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 108.5  12 | 2018-11-05T15:10:51+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 108.5  12 | 2018-11-05T15:10:51+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
 109.4  12 | 2018-11-05T15:10:52+0000 [-] Unhandled Error
 109.4  12 | 	Traceback (most recent call last):
 109.4  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('vortex.data.microsoft.com.localdomain', 1, 1)]
 109.4  12 | 
 109.4  12 | 2018-11-05T15:10:52+0000 [-] Unhandled Error
 109.4  12 | 	Traceback (most recent call last):
 109.4  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('vortex.data.microsoft.com.localdomain', 1, 1)]
 109.4  12 | 
 109.4  12 | 2018-11-05T15:10:52+0000 [-] (UDP Port 26867 Closed)
 109.4  12 | 2018-11-05T15:10:52+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729de48>
 109.5  12 | 2018-11-05T15:10:52+0000 [-] Unhandled Error
 109.5  12 | 	Traceback (most recent call last):
 109.5  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('vortex.data.microsoft.com.localdomain', 28, 1)]
 109.5  12 | 
 109.5  12 | 2018-11-05T15:10:52+0000 [-] Unhandled Error
 109.5  12 | 	Traceback (most recent call last):
 109.5  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('vortex.data.microsoft.com.localdomain', 28, 1)]
 109.5  12 | 
 109.5  12 | 2018-11-05T15:10:52+0000 [-] (UDP Port 36349 Closed)
 109.5  12 | 2018-11-05T15:10:52+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671ad390>
 110.5  19 | c : DNS request from ('10.100.102.3', 47443) to None: 47 bytes
 110.5  12 | 2018-11-05T15:10:53+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 110.6  12 | 2018-11-05T15:10:53+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 110.6  12 | 2018-11-05T15:10:53+0000 [stdout#info] A query: b'0.docs.google.com'
 110.6  12 | 2018-11-05T15:10:53+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 110.6  12 | 2018-11-05T15:10:53+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 110.6  12 | 2018-11-05T15:10:53+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 110.6  12 | 2018-11-05T15:10:53+0000 [-] DNSDatagramProtocol starting on 64275
 110.6  12 | 2018-11-05T15:10:53+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729dd68>
 110.7  12 | 2018-11-05T15:10:53+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 110.7  12 | 2018-11-05T15:10:53+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 110.7  12 | 2018-11-05T15:10:53+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 110.7  12 | 2018-11-05T15:10:54+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 110.7  19 | c : DNS request from ('10.100.102.3', 41087) to None: 49 bytes
 110.8  12 | 2018-11-05T15:10:54+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 110.8  12 | 2018-11-05T15:10:54+0000 [stdout#info] A query: b'clients4.google.com'
 110.8  12 | 2018-11-05T15:10:54+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 110.8  12 | 2018-11-05T15:10:54+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 110.8  12 | 2018-11-05T15:10:54+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 110.8  12 | 2018-11-05T15:10:54+0000 [-] DNSDatagramProtocol starting on 52647
 110.8  12 | 2018-11-05T15:10:54+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728ea20>
 111.5  19 | c : DNS request from ('10.100.102.3', 59451) to None: 35 bytes
 111.5  12 | 2018-11-05T15:10:54+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 111.5  12 | 2018-11-05T15:10:54+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 111.5  19 | c : DNS request from ('10.100.102.3', 37786) to None: 47 bytes
 111.5  12 | 2018-11-05T15:10:54+0000 [stdout#info] A query: b'0.docs.google.com'
 111.5  19 | c : DNS request from ('10.100.102.3', 39515) to None: 61 bytes
 111.5  12 | 2018-11-05T15:10:54+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 111.5  12 | 2018-11-05T15:10:54+0000 [stdout#info] A query: b'0.docs.google.com'
 111.5  12 | 2018-11-05T15:10:54+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 111.5  12 | 2018-11-05T15:10:54+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 111.6  12 | 2018-11-05T15:10:54+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 111.6  12 | 2018-11-05T15:10:54+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 111.6  12 | 2018-11-05T15:10:54+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 111.6  12 | 2018-11-05T15:10:54+0000 [-] DNSDatagramProtocol starting on 20823
 111.6  12 | 2018-11-05T15:10:54+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671c7080>
 111.6  12 | 2018-11-05T15:10:54+0000 [-] (UDP Port 64275 Closed)
 111.6  12 | 2018-11-05T15:10:54+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729dd68>
 111.7  19 | c : DNS request from ('10.100.102.3', 56011) to None: 37 bytes
 111.7  12 | 2018-11-05T15:10:55+0000 [stdout#info] A query: b'clients4.google.com'
 111.8  12 | 2018-11-05T15:10:55+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 111.8  19 | c : DNS request from ('10.100.102.3', 33676) to None: 49 bytes
 111.8  12 | 2018-11-05T15:10:55+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 111.8  12 | 2018-11-05T15:10:55+0000 [stdout#info] A query: b'clients4.google.com'
 111.9  12 | 2018-11-05T15:10:55+0000 [-] DNSDatagramProtocol starting on 26661
 111.9  12 | 2018-11-05T15:10:55+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672ab588>
 111.9  12 | 2018-11-05T15:10:55+0000 [-] (UDP Port 52647 Closed)
 111.9  12 | 2018-11-05T15:10:55+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728ea20>
 112.7  12 | 2018-11-05T15:10:55+0000 [-] DNSDatagramProtocol starting on 14253
 112.7  12 | 2018-11-05T15:10:55+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e518>
 112.7  12 | 2018-11-05T15:10:55+0000 [-] (UDP Port 20580 Closed)
 112.7  12 | 2018-11-05T15:10:56+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729d748>
 114.5  19 | c : DNS request from ('10.100.102.3', 49713) to None: 49 bytes
 114.5  12 | 2018-11-05T15:10:57+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 114.6  12 | 2018-11-05T15:10:57+0000 [-] DNSDatagramProtocol starting on 9801
 114.6  12 | 2018-11-05T15:10:57+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e4e0>
 114.6  12 | 2018-11-05T15:10:57+0000 [-] (UDP Port 20823 Closed)
 114.6  12 | 2018-11-05T15:10:57+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671c7080>
 114.9  12 | 2018-11-05T15:10:58+0000 [-] DNSDatagramProtocol starting on 38380
 114.9  12 | 2018-11-05T15:10:58+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672764a8>
 114.9  12 | 2018-11-05T15:10:58+0000 [-] (UDP Port 26661 Closed)
 114.9  12 | 2018-11-05T15:10:58+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672ab588>
 115.5  19 | c : DNS request from ('10.100.102.3', 58286) to None: 35 bytes
 115.5  12 | 2018-11-05T15:10:58+0000 [stdout#info] A query: b'0.docs.google.com'
 115.6  12 | 2018-11-05T15:10:58+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 115.6  12 | 2018-11-05T15:10:58+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 115.6  12 | 2018-11-05T15:10:58+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 115.7  19 | c : DNS request from ('10.100.102.3', 57721) to None: 37 bytes
 115.7  12 | 2018-11-05T15:10:59+0000 [stdout#info] A query: b'clients4.google.com'
 115.8  12 | 2018-11-05T15:10:59+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 115.8  12 | 2018-11-05T15:10:59+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 115.8  12 | 2018-11-05T15:10:59+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 116.5  19 | c : DNS request from ('10.100.102.3', 37786) to None: 47 bytes
 116.5  12 | 2018-11-05T15:10:59+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 116.5  12 | 2018-11-05T15:10:59+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 116.5  12 | 2018-11-05T15:10:59+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 116.5  12 | 2018-11-05T15:10:59+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 116.6  12 | 2018-11-05T15:10:59+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 116.6  12 | 2018-11-05T15:10:59+0000 [stdout#info] A query: b'0.docs.google.com'
 116.6  12 | 2018-11-05T15:10:59+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 116.6  12 | 2018-11-05T15:10:59+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 116.6  12 | 2018-11-05T15:10:59+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 116.7  12 | 2018-11-05T15:11:00+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 116.8  19 | c : DNS request from ('10.100.102.3', 33676) to None: 49 bytes
 116.8  12 | 2018-11-05T15:11:00+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 116.8  12 | 2018-11-05T15:11:00+0000 [stdout#info] A query: b'clients4.google.com'
 116.9  12 | 2018-11-05T15:11:00+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 116.9  12 | 2018-11-05T15:11:00+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 116.9  12 | 2018-11-05T15:11:00+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 117.7  12 | 2018-11-05T15:11:00+0000 [-] Unhandled Error
 117.7  12 | 	Traceback (most recent call last):
 117.7  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('api.mixpanel.com.localdomain', 1, 1)]
 117.7  12 | 
 117.7  12 | 2018-11-05T15:11:00+0000 [-] Unhandled Error
 117.7  12 | 	Traceback (most recent call last):
 117.7  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('api.mixpanel.com.localdomain', 1, 1)]
 117.7  12 | 
 117.7  12 | 2018-11-05T15:11:00+0000 [-] (UDP Port 50560 Closed)
 117.7  12 | 2018-11-05T15:11:00+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bbb70>
 117.8  12 | 2018-11-05T15:11:01+0000 [-] Unhandled Error
 117.8  12 | 	Traceback (most recent call last):
 117.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('www.msftconnecttest.com.localdomain', 1, 1)]
 117.8  12 | 
 117.8  12 | 2018-11-05T15:11:01+0000 [-] Unhandled Error
 117.8  12 | 	Traceback (most recent call last):
 117.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('www.msftconnecttest.com.localdomain', 1, 1)]
 117.8  12 | 
 117.8  12 | 2018-11-05T15:11:01+0000 [-] Unhandled Error
 117.8  12 | 	Traceback (most recent call last):
 117.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('www.msftconnecttest.com.localdomain', 1, 1)]
 117.8  12 | 
 117.8  12 | 2018-11-05T15:11:01+0000 [-] Unhandled Error
 117.8  12 | 	Traceback (most recent call last):
 117.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('www.msftconnecttest.com.localdomain', 1, 1)]
 117.8  12 | 
 117.8  12 | 2018-11-05T15:11:01+0000 [-] (UDP Port 14452 Closed)
 117.8  12 | 2018-11-05T15:11:01+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86729df60>
 119.5  19 | c : DNS request from ('10.100.102.3', 49713) to None: 49 bytes
 119.5  12 | 2018-11-05T15:11:02+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 119.5  19 | c : DNS request from ('10.100.102.3', 47323) to None: 61 bytes
 119.5  12 | 2018-11-05T15:11:02+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 119.5  12 | 2018-11-05T15:11:02+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 119.5  12 | 2018-11-05T15:11:02+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 119.9  19 | c : Accept TCP: 10.100.102.3:33832 -> 172.30.249.217:443.
 119.9  19 | c : Accept TCP: 10.100.102.3:33838 -> 172.30.249.217:443.
 119.9  19 | c : Accept TCP: 10.100.102.3:33840 -> 172.30.249.217:443.
 119.9  19 | c : Accept TCP: 10.100.102.3:33842 -> 172.30.249.217:443.
 119.9  19 | c : Accept TCP: 10.100.102.3:33856 -> 172.30.249.217:443.
 119.9  19 | c : Accept TCP: 10.100.102.3:33858 -> 172.30.249.217:443.
 120.0  19 | c : SW#10:10.100.102.3:33832: uwrite: got EPIPE
 120.0  19 | c : warning: closed channel 166 got cmd=TCP_EOF len=0
 120.0  19 |  s: warning: closed channel 166 got cmd=TCP_STOP_SENDING len=0
 120.0  19 | c : SW#10:10.100.102.3:33832: deleting (17 remain)
 120.0  19 | c : SW#10:10.100.102.3:33832: error was: nowrite: [Errno 107] Transport endpoint is not connected
 120.0  19 | c : SW'unknown':Mux#166: deleting (16 remain)
 120.0  19 | c : Accept TCP: 10.100.102.3:33868 -> 172.30.249.217:443.
 120.0  19 | c : Accept TCP: 10.100.102.3:33870 -> 172.30.249.217:443.
 120.1  19 |  s: SW'unknown':Mux#166: deleting (17 remain)
 120.1  19 |  s: SW#50:172.30.249.217:443: deleting (16 remain)
 120.1  19 | c : warning: closed channel 168 got cmd=TCP_DATA len=31
 120.1  19 | c : Accept TCP: 10.100.102.3:33880 -> 172.30.249.217:443.
 120.2  19 | c : SW#13:10.100.102.3:33840: deleting (21 remain)
 120.2  19 | c : SW#13:10.100.102.3:33840: error was: uread: [Errno 104] Connection reset by peer
 120.2  19 | c : SW'unknown':Mux#168: deleting (20 remain)
 120.2  19 | c : SW#12:10.100.102.3:33838: deleting (19 remain)
 120.2  19 | c : SW#12:10.100.102.3:33838: error was: uread: [Errno 104] Connection reset by peer
 120.2  19 | c : SW'unknown':Mux#167: deleting (18 remain)
 120.2  19 | c : SW#15:10.100.102.3:33842: uwrite: got EPIPE
 120.2  19 | c : Accept TCP: 10.100.102.3:33886 -> 172.30.249.217:443.
 120.3  19 |  s: warning: closed channel 169 got cmd=TCP_STOP_SENDING len=0
 120.3  19 | c : warning: closed channel 169 got cmd=TCP_EOF len=0
 120.4  19 | c : SW#16:10.100.102.3:33856: deleting (19 remain)
 120.4  19 | c : SW#16:10.100.102.3:33856: error was: uread: [Errno 104] Connection reset by peer
 120.4  19 | c : SW'unknown':Mux#170: deleting (18 remain)
 120.4  19 | c : SW#15:10.100.102.3:33842: deleting (17 remain)
 120.4  19 | c : SW#15:10.100.102.3:33842: error was: nowrite: [Errno 107] Transport endpoint is not connected
 120.4  19 | c : SW'unknown':Mux#169: deleting (16 remain)
 120.4  19 |  s: SW'unknown':Mux#167: deleting (23 remain)
 120.4  19 |  s: SW#51:172.30.249.217:443: deleting (22 remain)
 120.4  19 |  s: SW'unknown':Mux#169: deleting (21 remain)
 120.4  19 |  s: SW#53:172.30.249.217:443: deleting (20 remain)
 120.4  19 |  s: SW'unknown':Mux#170: deleting (19 remain)
 120.4  19 |  s: SW#7:172.30.249.217:443: deleting (18 remain)
 120.4  19 | c : Accept TCP: 10.100.102.3:33894 -> 172.30.249.217:443.
 120.4  19 | c : Accept TCP: 10.100.102.3:33892 -> 172.30.249.217:443.
 120.4  19 | c : SW#17:10.100.102.3:33858: deleting (19 remain)
 120.4  19 | c : SW#17:10.100.102.3:33858: error was: uread: [Errno 104] Connection reset by peer
 120.4  19 | c : SW'unknown':Mux#171: deleting (18 remain)
 120.4  19 | c : SW#10:10.100.102.3:33868: deleting (17 remain)
 120.4  19 | c : SW#10:10.100.102.3:33868: error was: uread: [Errno 104] Connection reset by peer
 120.4  19 | c : SW'unknown':Mux#172: deleting (16 remain)
 120.4  19 | c : SW#18:10.100.102.3:33870: deleting (15 remain)
 120.4  19 | c : SW#18:10.100.102.3:33870: error was: uread: [Errno 104] Connection reset by peer
 120.4  19 | c : SW'unknown':Mux#173: deleting (14 remain)
 120.5  19 | c : warning: closed channel 172 got cmd=TCP_DATA len=31
 120.5  19 | c : DNS request from ('10.100.102.3', 50904) to None: 49 bytes
 120.5  19 | c : SW#19:10.100.102.3:33880: uwrite: got EPIPE
 120.5  19 | c : warning: closed channel 174 got cmd=TCP_EOF len=0
 120.5  12 | 2018-11-05T15:11:03+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 120.5  19 | c : DNS request from ('10.100.102.3', 58286) to None: 35 bytes
 120.6  12 | 2018-11-05T15:11:03+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 120.6  12 | 2018-11-05T15:11:03+0000 [stdout#info] A query: b'0.docs.google.com'
 120.7  19 |  s: warning: closed channel 174 got cmd=TCP_STOP_SENDING len=0
 120.7  19 | c : DNS request from ('10.100.102.3', 60941) to None: 47 bytes
 120.7  19 | c : SW#12:10.100.102.3:33886: uwrite: got EPIPE
 120.7  19 | c : DNS request from ('10.100.102.3', 57721) to None: 37 bytes
 120.8  12 | 2018-11-05T15:11:03+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 120.8  19 |  s: warning: closed channel 175 got cmd=TCP_STOP_SENDING len=0
 120.8  19 | c : warning: closed channel 175 got cmd=TCP_EOF len=0
 120.8  19 | c : SW'unknown':Mux#174: deleting (13 remain)
 120.8  19 | c : SW#19:10.100.102.3:33880: deleting (12 remain)
 120.8  19 | c : SW#19:10.100.102.3:33880: error was: nowrite: [Errno 107] Transport endpoint is not connected
 120.8  19 | c : SW'unknown':Mux#175: deleting (11 remain)
 120.8  19 | c : SW#12:10.100.102.3:33886: deleting (10 remain)
 120.8  19 | c : SW#12:10.100.102.3:33886: error was: nowrite: [Errno 107] Transport endpoint is not connected
 120.8  19 | c : DNS request from ('10.100.102.3', 40258) to None: 49 bytes
 120.8  12 | 2018-11-05T15:11:04+0000 [stdout#info] A query: b'0.docs.google.com'
 120.8  12 | 2018-11-05T15:11:04+0000 [stdout#info] A query: b'clients4.google.com'
 120.8  12 | 2018-11-05T15:11:04+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 120.9  19 |  s: SW'unknown':Mux#172: deleting (21 remain)
 120.9  19 |  s: SW#20:172.30.249.217:443: deleting (20 remain)
 120.9  19 |  s: SW'unknown':Mux#173: deleting (19 remain)
 120.9  19 |  s: SW#22:172.30.249.217:443: deleting (18 remain)
 120.9  19 |  s: SW'unknown':Mux#174: deleting (17 remain)
 120.9  19 |  s: SW#23:172.30.249.217:443: deleting (16 remain)
 120.9  12 | 2018-11-05T15:11:04+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 120.9  12 | 2018-11-05T15:11:04+0000 [stdout#info] A query: b'clients4.google.com'
 120.9 TEL | [34] Running: sudo -n echo -n
 121.1  19 |  s: warning: closed channel 177 got cmd=TCP_STOP_SENDING len=0
 121.1  19 | c : warning: closed channel 177 got cmd=TCP_DATA len=31
 121.1  19 | c : warning: closed channel 177 got cmd=TCP_EOF len=0
 121.1  19 | c : SW#13:10.100.102.3:33894: uwrite: got EPIPE
 121.1  19 | c : warning: closed channel 176 got cmd=TCP_EOF len=0
 121.1  19 |  s: warning: closed channel 176 got cmd=TCP_STOP_SENDING len=0
 121.5  19 | c : DNS request from ('10.100.102.3', 40345) to None: 35 bytes
 121.5  12 | 2018-11-05T15:11:04+0000 [stdout#info] A query: b'0.docs.google.com'
 121.6 TEL | (proxy checking local liveness)
 121.6  12 | 2018-11-05T15:11:04+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 121.6  12 | 2018-11-05T15:11:04+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 121.6  12 | 2018-11-05T15:11:04+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 121.6  12 | 2018-11-05T15:11:04+0000 [Poll#info] Checkpoint
 121.7  19 | c : DNS request from ('10.100.102.3', 60099) to None: 37 bytes
 121.7  12 | 2018-11-05T15:11:05+0000 [stdout#info] A query: b'clients4.google.com'
 121.8  12 | 2018-11-05T15:11:05+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 121.8  12 | 2018-11-05T15:11:05+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 121.8  12 | 2018-11-05T15:11:05+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 124.5  12 | 2018-11-05T15:11:07+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 124.5  19 | c : DNS request from ('10.100.102.3', 47323) to None: 61 bytes
 124.5  12 | 2018-11-05T15:11:07+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 124.5  12 | 2018-11-05T15:11:07+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 124.5  12 | 2018-11-05T15:11:07+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 124.6  12 | 2018-11-05T15:11:07+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 124.6  12 | 2018-11-05T15:11:07+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 125.5  19 | c : DNS request from ('10.100.102.3', 50904) to None: 49 bytes
 125.5  12 | 2018-11-05T15:11:08+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 125.5  12 | 2018-11-05T15:11:08+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 125.5  19 | c : DNS request from ('10.100.102.3', 44235) to None: 61 bytes
 125.5  12 | 2018-11-05T15:11:08+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 125.5  12 | 2018-11-05T15:11:08+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 125.6  12 | 2018-11-05T15:11:08+0000 [-] DNSDatagramProtocol starting on 64171
 125.6  12 | 2018-11-05T15:11:08+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8673547f0>
 125.6  12 | 2018-11-05T15:11:08+0000 [-] (UDP Port 9801 Closed)
 125.6  12 | 2018-11-05T15:11:08+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e4e0>
 125.7  12 | 2018-11-05T15:11:08+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 125.7  19 | c : DNS request from ('10.100.102.3', 60941) to None: 47 bytes
 125.7  12 | 2018-11-05T15:11:08+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 125.7  12 | 2018-11-05T15:11:08+0000 [stdout#info] A query: b'0.docs.google.com'
 125.8  19 | c : DNS request from ('10.100.102.3', 40258) to None: 49 bytes
 125.8  12 | 2018-11-05T15:11:09+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 125.8  12 | 2018-11-05T15:11:09+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 125.8  12 | 2018-11-05T15:11:09+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 125.8  12 | 2018-11-05T15:11:09+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 125.8  12 | 2018-11-05T15:11:09+0000 [stdout#info] A query: b'clients4.google.com'
 125.9  12 | 2018-11-05T15:11:09+0000 [-] DNSDatagramProtocol starting on 60640
 125.9  12 | 2018-11-05T15:11:09+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6320>
 125.9  12 | 2018-11-05T15:11:09+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 125.9  12 | 2018-11-05T15:11:09+0000 [-] (UDP Port 38380 Closed)
 125.9  12 | 2018-11-05T15:11:09+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672764a8>
 126.0  12 | 2018-11-05T15:11:09+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 126.0  12 | 2018-11-05T15:11:09+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 126.0  12 | 2018-11-05T15:11:09+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 126.5  19 | c : DNS request from ('10.100.102.3', 40345) to None: 35 bytes
 126.5  12 | 2018-11-05T15:11:09+0000 [stdout#info] A query: b'0.docs.google.com'
 126.5  19 | c : DNS request from ('10.100.102.3', 38683) to None: 47 bytes
 126.5  12 | 2018-11-05T15:11:09+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 126.6  12 | 2018-11-05T15:11:09+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 126.6  12 | 2018-11-05T15:11:09+0000 [stdout#info] A query: b'0.docs.google.com'
 126.7  19 | c : DNS request from ('10.100.102.3', 60099) to None: 37 bytes
 126.7  12 | 2018-11-05T15:11:10+0000 [stdout#info] A query: b'clients4.google.com'
 126.7  19 | c : DNS request from ('10.100.102.3', 45547) to None: 49 bytes
 126.7  12 | 2018-11-05T15:11:10+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 126.7  12 | 2018-11-05T15:11:10+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 126.7  12 | 2018-11-05T15:11:10+0000 [stdout#info] A query: b'clients4.google.com'
 128.5  19 | c : DNS request from ('10.100.102.3', 42232) to None: 57 bytes
 128.5  12 | 2018-11-05T15:11:11+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 129.5  12 | 2018-11-05T15:11:12+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 129.5  12 | 2018-11-05T15:11:12+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 129.5  12 | 2018-11-05T15:11:12+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 130.5  12 | 2018-11-05T15:11:13+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 130.5  19 | c : DNS request from ('10.100.102.3', 44235) to None: 61 bytes
 130.5  12 | 2018-11-05T15:11:13+0000 [stdout#info] Updated query of type 1 from b'browser.pipe.aria.microsoft.com.localdomain' to b'browser.pipe.aria.microsoft.com'
 130.5  12 | 2018-11-05T15:11:13+0000 [stdout#info] A query: b'browser.pipe.aria.microsoft.com'
 130.5  12 | 2018-11-05T15:11:13+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 130.5  12 | 2018-11-05T15:11:13+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 130.5  12 | 2018-11-05T15:11:13+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 130.7  12 | 2018-11-05T15:11:13+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 130.7  12 | 2018-11-05T15:11:13+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 130.7  12 | 2018-11-05T15:11:13+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 130.9  12 | 2018-11-05T15:11:14+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 130.9  12 | 2018-11-05T15:11:14+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 130.9  12 | 2018-11-05T15:11:14+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 131.5  19 | c : DNS request from ('10.100.102.3', 33255) to None: 33 bytes
 131.5  19 | c : DNS request from ('10.100.102.3', 50917) to None: 35 bytes
 131.5  12 | 2018-11-05T15:11:14+0000 [stdout#info] A query: b'ssl.gstatic.com'
 131.5  12 | 2018-11-05T15:11:14+0000 [stdout#info] A query: b'0.docs.google.com'
 131.5  19 | c : DNS request from ('10.100.102.3', 38683) to None: 47 bytes
 131.5  12 | 2018-11-05T15:11:14+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 131.6  12 | 2018-11-05T15:11:14+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 131.6  12 | 2018-11-05T15:11:14+0000 [stdout#info] A query: b'0.docs.google.com'
 131.6  12 | 2018-11-05T15:11:14+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 131.6  12 | 2018-11-05T15:11:14+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 131.6  12 | 2018-11-05T15:11:14+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 131.7  12 | 2018-11-05T15:11:15+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 131.7  19 | c : SW#15:10.100.102.3:33892: deleting (9 remain)
 131.7  19 | c : SW#15:10.100.102.3:33892: error was: uread: [Errno 104] Connection reset by peer
 131.7  19 | c : SW'unknown':Mux#177: deleting (8 remain)
 131.7  19 | c : SW#13:10.100.102.3:33894: deleting (7 remain)
 131.7  19 | c : SW#13:10.100.102.3:33894: error was: nowrite: [Errno 107] Transport endpoint is not connected
 131.7  19 | c : SW'unknown':Mux#176: deleting (6 remain)
 131.7  19 | c : DNS request from ('10.100.102.3', 45547) to None: 49 bytes
 131.7  12 | 2018-11-05T15:11:15+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 131.7  12 | 2018-11-05T15:11:15+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 131.7  12 | 2018-11-05T15:11:15+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 131.7  12 | 2018-11-05T15:11:15+0000 [stdout#info] Updated query of type 1 from b'clients4.google.com.localdomain' to b'clients4.google.com'
 131.7  12 | 2018-11-05T15:11:15+0000 [stdout#info] A query: b'clients4.google.com'
 133.5  19 | c : DNS request from ('10.100.102.3', 42232) to None: 57 bytes
 133.5  12 | 2018-11-05T15:11:16+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 133.5  12 | 2018-11-05T15:11:16+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 133.5  19 | c : DNS request from ('10.100.102.3', 51360) to None: 69 bytes
 133.5  12 | 2018-11-05T15:11:16+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
 133.5  12 | 2018-11-05T15:11:16+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 134.5  19 | c : DNS request from ('10.100.102.3', 37100) to None: 57 bytes
 134.5  12 | 2018-11-05T15:11:17+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 135.5  12 | 2018-11-05T15:11:18+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 135.5  12 | 2018-11-05T15:11:18+0000 [stdout#info] Failed to lookup b'browser.pipe.aria.microsoft.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 135.5  12 | 2018-11-05T15:11:18+0000 [stdout#info] ], falling back to b'browser.pipe.aria.microsoft.com.localdomain'
 136.5  19 | c : DNS request from ('10.100.102.3', 33255) to None: 33 bytes
 136.5  19 | c : DNS request from ('10.100.102.3', 50917) to None: 35 bytes
 136.5  12 | 2018-11-05T15:11:19+0000 [stdout#info] A query: b'ssl.gstatic.com'
 136.5  12 | 2018-11-05T15:11:19+0000 [stdout#info] A query: b'0.docs.google.com'
 136.5  12 | 2018-11-05T15:11:19+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 136.5  19 | c : DNS request from ('10.100.102.3', 53166) to None: 45 bytes
 136.5  19 | c : DNS request from ('10.100.102.3', 43437) to None: 47 bytes
 136.5  12 | 2018-11-05T15:11:19+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 136.6  12 | 2018-11-05T15:11:19+0000 [stdout#info] Updated query of type 1 from b'ssl.gstatic.com.localdomain' to b'ssl.gstatic.com'
 136.6  12 | 2018-11-05T15:11:19+0000 [stdout#info] A query: b'ssl.gstatic.com'
 136.6  12 | 2018-11-05T15:11:19+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 136.6  12 | 2018-11-05T15:11:19+0000 [stdout#info] A query: b'0.docs.google.com'
 136.6  12 | 2018-11-05T15:11:19+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 136.6  12 | 2018-11-05T15:11:19+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 136.6  12 | 2018-11-05T15:11:19+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 136.7  12 | 2018-11-05T15:11:20+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 136.8  12 | 2018-11-05T15:11:20+0000 [stdout#info] Failed to lookup b'clients4.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 136.8  12 | 2018-11-05T15:11:20+0000 [stdout#info] ], falling back to b'clients4.google.com.localdomain'
 137.5  19 | c : DNS request from ('10.100.102.3', 51794) to None: 33 bytes
 137.5  19 | c : DNS request from ('10.100.102.3', 39997) to None: 35 bytes
 137.5  12 | 2018-11-05T15:11:20+0000 [stdout#info] A query: b'ssl.gstatic.com'
 137.5  12 | 2018-11-05T15:11:20+0000 [stdout#info] A query: b'0.docs.google.com'
 138.5  12 | 2018-11-05T15:11:21+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 138.5  19 | c : DNS request from ('10.100.102.3', 51360) to None: 69 bytes
 138.6  12 | 2018-11-05T15:11:21+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
 138.6  12 | 2018-11-05T15:11:21+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 138.6  12 | 2018-11-05T15:11:21+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 138.6  12 | 2018-11-05T15:11:21+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 138.6  12 | 2018-11-05T15:11:21+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
 139.5  19 | c : DNS request from ('10.100.102.3', 37100) to None: 57 bytes
 139.5  12 | 2018-11-05T15:11:22+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 139.5  19 | c : DNS request from ('10.100.102.3', 54363) to None: 69 bytes
 139.5  12 | 2018-11-05T15:11:22+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 139.5  12 | 2018-11-05T15:11:22+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
 139.5  12 | 2018-11-05T15:11:22+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 141.5  19 | c : DNS request from ('10.100.102.3', 43437) to None: 47 bytes
 141.5  12 | 2018-11-05T15:11:24+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 141.5  19 | c : DNS request from ('10.100.102.3', 53166) to None: 45 bytes
 141.6  12 | 2018-11-05T15:11:24+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 141.6  12 | 2018-11-05T15:11:24+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 141.6  12 | 2018-11-05T15:11:24+0000 [stdout#info] A query: b'0.docs.google.com'
 141.6  12 | 2018-11-05T15:11:24+0000 [stdout#info] Updated query of type 1 from b'ssl.gstatic.com.localdomain' to b'ssl.gstatic.com'
 141.6  12 | 2018-11-05T15:11:24+0000 [stdout#info] A query: b'ssl.gstatic.com'
 141.7  12 | 2018-11-05T15:11:24+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 141.7  12 | 2018-11-05T15:11:24+0000 [stdout#info] Failed to lookup b'ssl.gstatic.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 141.7  12 | 2018-11-05T15:11:24+0000 [stdout#info] ], falling back to b'ssl.gstatic.com.localdomain'
 141.7  12 | 2018-11-05T15:11:24+0000 [-] DNSDatagramProtocol starting on 7171
 141.7  12 | 2018-11-05T15:11:24+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867294a20>
 141.7  12 | 2018-11-05T15:11:24+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 141.7  12 | 2018-11-05T15:11:24+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 141.7  12 | 2018-11-05T15:11:24+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 142.5  19 | c : DNS request from ('10.100.102.3', 39997) to None: 35 bytes
 142.5  19 | c : DNS request from ('10.100.102.3', 51794) to None: 33 bytes
 142.5  12 | 2018-11-05T15:11:25+0000 [stdout#info] A query: b'0.docs.google.com'
 142.5  12 | 2018-11-05T15:11:25+0000 [stdout#info] A query: b'ssl.gstatic.com'
 142.5  12 | 2018-11-05T15:11:25+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 142.5  12 | 2018-11-05T15:11:25+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 142.5  19 | c : DNS request from ('10.100.102.3', 54662) to None: 45 bytes
 142.6  19 |  s: SW'unknown':Mux#177: deleting (15 remain)
 142.6  19 |  s: SW#26:172.30.249.217:443: deleting (14 remain)
 142.6  19 |  s: SW'unknown':Mux#176: deleting (13 remain)
 142.6  19 |  s: SW#7:172.30.249.217:443: deleting (12 remain)
 142.6  19 | c : DNS request from ('10.100.102.3', 58508) to None: 47 bytes
 142.6  12 | 2018-11-05T15:11:25+0000 [stdout#info] Updated query of type 1 from b'ssl.gstatic.com.localdomain' to b'ssl.gstatic.com'
 142.6  12 | 2018-11-05T15:11:25+0000 [stdout#info] A query: b'ssl.gstatic.com'
 142.7  12 | 2018-11-05T15:11:25+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 142.7  12 | 2018-11-05T15:11:25+0000 [stdout#info] A query: b'0.docs.google.com'
 142.7  12 | 2018-11-05T15:11:25+0000 [-] DNSDatagramProtocol starting on 19384
 142.7  12 | 2018-11-05T15:11:25+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867294d68>
 142.7  12 | 2018-11-05T15:11:25+0000 [-] (UDP Port 7171 Closed)
 142.7  12 | 2018-11-05T15:11:25+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867294a20>
 142.8  12 | 2018-11-05T15:11:26+0000 [-] Unhandled Error
 142.8  12 | 	Traceback (most recent call last):
 142.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('plugins.jetbrains.com.localdomain', 1, 1)]
 142.8  12 | 
 142.8  12 | 2018-11-05T15:11:26+0000 [-] Unhandled Error
 142.8  12 | 	Traceback (most recent call last):
 142.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('plugins.jetbrains.com.localdomain', 1, 1)]
 142.8  12 | 
 142.8  12 | 2018-11-05T15:11:26+0000 [-] (UDP Port 59761 Closed)
 142.8  12 | 2018-11-05T15:11:26+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671bbba8>
 143.6  12 | 2018-11-05T15:11:26+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 143.6  12 | 2018-11-05T15:11:26+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 143.6  12 | 2018-11-05T15:11:26+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
 144.5  19 | c : DNS request from ('10.100.102.3', 54363) to None: 69 bytes
 144.5  12 | 2018-11-05T15:11:27+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 144.5  12 | 2018-11-05T15:11:27+0000 [stdout#info] Updated query of type 1 from b'db5-client-s.gateway.messenger.live.com.localdomain' to b'db5-client-s.gateway.messenger.live.com'
 144.6  12 | 2018-11-05T15:11:27+0000 [stdout#info] A query: b'db5-client-s.gateway.messenger.live.com'
 144.6  12 | 2018-11-05T15:11:27+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 144.6  12 | 2018-11-05T15:11:27+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 144.6  12 | 2018-11-05T15:11:27+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
 145.5  19 | c : DNS request from ('10.100.102.3', 50713) to None: 35 bytes
 145.5  19 | c : DNS request from ('10.100.102.3', 50713) to None: 35 bytes
 145.5  12 | 2018-11-05T15:11:28+0000 [stdout#info] A query: b'fedoraproject.org'
 145.5  12 | 2018-11-05T15:11:28+0000 [stdout#info] AAAA query, sending back A instead: b'fedoraproject.org'
 145.5  12 | 2018-11-05T15:11:28+0000 [stdout#info] A query: b'fedoraproject.org'
 145.7  12 | 2018-11-05T15:11:28+0000 [-] DNSDatagramProtocol starting on 42016
 145.7  12 | 2018-11-05T15:11:28+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672e58d0>
 145.7  12 | 2018-11-05T15:11:28+0000 [-] (UDP Port 19384 Closed)
 145.7  12 | 2018-11-05T15:11:28+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa867294d68>
 146.5  19 | c : DNS request from ('10.100.102.3', 36125) to None: 35 bytes
 146.5  19 | c : DNS request from ('10.100.102.3', 60816) to None: 33 bytes
 146.5  12 | 2018-11-05T15:11:29+0000 [stdout#info] A query: b'0.docs.google.com'
 146.5  12 | 2018-11-05T15:11:29+0000 [stdout#info] A query: b'ssl.gstatic.com'
 146.7  12 | 2018-11-05T15:11:29+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 146.7  12 | 2018-11-05T15:11:29+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 146.7  12 | 2018-11-05T15:11:29+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 146.7  12 | 2018-11-05T15:11:29+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 146.7  12 | 2018-11-05T15:11:29+0000 [stdout#info] Failed to lookup b'ssl.gstatic.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 146.7  12 | 2018-11-05T15:11:29+0000 [stdout#info] ], falling back to b'ssl.gstatic.com.localdomain'
 147.5  12 | 2018-11-05T15:11:30+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 147.5  19 | c : DNS request from ('10.100.102.3', 54662) to None: 45 bytes
 147.6  12 | 2018-11-05T15:11:30+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 147.6  12 | 2018-11-05T15:11:30+0000 [stdout#info] Updated query of type 1 from b'ssl.gstatic.com.localdomain' to b'ssl.gstatic.com'
 147.6  12 | 2018-11-05T15:11:30+0000 [stdout#info] A query: b'ssl.gstatic.com'
 147.6  19 | c : DNS request from ('10.100.102.3', 58508) to None: 47 bytes
 147.6  12 | 2018-11-05T15:11:30+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 147.6  12 | 2018-11-05T15:11:30+0000 [stdout#info] A query: b'0.docs.google.com'
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Unhandled Error
 147.6  12 | 	Traceback (most recent call last):
 147.6  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('browser.pipe.aria.microsoft.com.localdomain', 1, 1)]
 147.6  12 | 
 147.6  12 | 2018-11-05T15:11:30+0000 [-] (UDP Port 63019 Closed)
 147.6  12 | 2018-11-05T15:11:30+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dd978>
 147.8  12 | 2018-11-05T15:11:31+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 147.8  12 | 2018-11-05T15:11:31+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 147.8  12 | 2018-11-05T15:11:31+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 147.8  12 | 2018-11-05T15:11:31+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 147.8  12 | 2018-11-05T15:11:31+0000 [stdout#info] Failed to lookup b'ssl.gstatic.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 147.8  12 | 2018-11-05T15:11:31+0000 [stdout#info] ], falling back to b'ssl.gstatic.com.localdomain'
 149.6  12 | 2018-11-05T15:11:32+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 149.6  12 | 2018-11-05T15:11:32+0000 [stdout#info] Failed to lookup b'db5-client-s.gateway.messenger.live.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 149.6  12 | 2018-11-05T15:11:32+0000 [stdout#info] ], falling back to b'db5-client-s.gateway.messenger.live.com.localdomain'
 149.9  19 | c : Accept TCP: 10.100.102.3:34292 -> 172.30.249.217:443.
 149.9  19 | c : Accept TCP: 10.100.102.3:34290 -> 172.30.249.217:443.
 149.9  19 | c : Accept TCP: 10.100.102.3:34294 -> 172.30.249.217:443.
 149.9  19 | c : Accept TCP: 10.100.102.3:34308 -> 172.30.249.217:443.
 149.9  19 | c : Accept TCP: 10.100.102.3:34310 -> 172.30.249.217:443.
 150.0  19 | c : SW#10:10.100.102.3:34292: uwrite: got EPIPE
 150.0  19 | c : warning: closed channel 225 got cmd=TCP_EOF len=0
 150.0  19 | c : Accept TCP: 10.100.102.3:34320 -> 172.30.249.217:443.
 150.0  19 | c : Accept TCP: 10.100.102.3:34322 -> 172.30.249.217:443.
 150.0  19 | c : SW#10:10.100.102.3:34292: deleting (19 remain)
 150.0  19 | c : SW#10:10.100.102.3:34292: error was: nowrite: [Errno 107] Transport endpoint is not connected
 150.0  19 | c : SW'unknown':Mux#225: deleting (18 remain)
 150.1  19 |  s: warning: closed channel 225 got cmd=TCP_STOP_SENDING len=0
 150.1  19 | c : SW#12:10.100.102.3:34290: uwrite: got EPIPE
 150.1  19 |  s: SW'unknown':Mux#225: deleting (25 remain)
 150.1  19 |  s: SW#22:172.30.249.217:443: deleting (24 remain)
 150.1  19 |  s: SW'unknown':Mux#226: deleting (23 remain)
 150.1  19 |  s: SW#23:172.30.249.217:443: deleting (22 remain)
 150.1  19 | c : Accept TCP: 10.100.102.3:34332 -> 172.30.249.217:443.
 150.1  19 | c : Accept TCP: 10.100.102.3:34334 -> 172.30.249.217:443.
 150.1  19 | c : Accept TCP: 10.100.102.3:34336 -> 172.30.249.217:443.
 150.1  19 | c : SW#12:10.100.102.3:34290: deleting (23 remain)
 150.1  19 | c : SW#12:10.100.102.3:34290: error was: nowrite: [Errno 107] Transport endpoint is not connected
 150.1  19 | c : SW'unknown':Mux#226: deleting (22 remain)
 150.1  19 | c : SW#13:10.100.102.3:34294: deleting (21 remain)
 150.1  19 | c : SW#13:10.100.102.3:34294: error was: uread: [Errno 104] Connection reset by peer
 150.1  19 | c : SW'unknown':Mux#227: deleting (20 remain)
 150.1  19 | c : SW#16:10.100.102.3:34310: deleting (19 remain)
 150.1  19 | c : SW#16:10.100.102.3:34310: error was: uread: [Errno 104] Connection reset by peer
 150.1  19 | c : SW'unknown':Mux#229: deleting (18 remain)
 150.1  19 | c : SW#15:10.100.102.3:34308: deleting (17 remain)
 150.1  19 | c : SW#15:10.100.102.3:34308: error was: uread: [Errno 104] Connection reset by peer
 150.1  19 | c : SW'unknown':Mux#228: deleting (16 remain)
 150.2  19 | c : SW#18:10.100.102.3:34322: uwrite: got EPIPE
 150.2  19 | c : Accept TCP: 10.100.102.3:34350 -> 172.30.249.217:443.
 150.2  19 | c : Accept TCP: 10.100.102.3:34352 -> 172.30.249.217:443.
 150.3  19 |  s: warning: closed channel 231 got cmd=TCP_STOP_SENDING len=0
 150.3  19 | c : warning: closed channel 231 got cmd=TCP_EOF len=0
 150.3  19 |  s: SW'unknown':Mux#229: deleting (31 remain)
 150.3  19 |  s: SW#27:172.30.249.217:443: deleting (30 remain)
 150.3  19 |  s: SW'unknown':Mux#228: deleting (29 remain)
 150.3  19 |  s: SW#26:172.30.249.217:443: deleting (28 remain)
 150.3  19 |  s: SW'unknown':Mux#227: deleting (27 remain)
 150.3  19 |  s: SW#25:172.30.249.217:443: deleting (26 remain)
 150.3  19 |  s: SW'unknown':Mux#231: deleting (25 remain)
 150.3  19 |  s: SW#17:172.30.249.217:443: deleting (24 remain)
 150.3  19 | c : SW#18:10.100.102.3:34322: deleting (19 remain)
 150.3  19 | c : SW#18:10.100.102.3:34322: error was: nowrite: [Errno 107] Transport endpoint is not connected
 150.3  19 | c : SW'unknown':Mux#231: deleting (18 remain)
 150.3  19 | c : SW#17:10.100.102.3:34320: deleting (17 remain)
 150.3  19 | c : SW#17:10.100.102.3:34320: error was: uread: [Errno 104] Connection reset by peer
 150.3  19 | c : SW'unknown':Mux#230: deleting (16 remain)
 150.4  19 |  s: SW#15:172.30.249.217:443: deleting (23 remain)
 150.5  19 |  s: SW'unknown':Mux#123: deleting (22 remain)
 150.5  19 |  s: SW'unknown':Mux#124: deleting (21 remain)
 150.5  19 |  s: SW#16:172.30.249.217:443: deleting (20 remain)
 150.5  19 |  s: SW'unknown':Mux#168: deleting (19 remain)
 150.5  19 |  s: SW#52:172.30.249.217:443: deleting (18 remain)
 150.5  19 |  s: SW'unknown':Mux#171: deleting (17 remain)
 150.5  19 |  s: SW#14:172.30.249.217:443: deleting (16 remain)
 150.5  19 |  s: SW#24:172.30.249.217:443: deleting (15 remain)
 150.5  19 |  s: SW'unknown':Mux#175: deleting (14 remain)
 150.5  19 |  s: SW'unknown':Mux#230: deleting (13 remain)
 150.5  19 |  s: SW#8:172.30.249.217:443: deleting (12 remain)
 150.5  19 | c : SW#13:10.100.102.3:34352: uwrite: got EPIPE
 150.5  19 | c : DNS request from ('10.100.102.3', 50713) to None: 35 bytes
 150.5  19 | c : DNS request from ('10.100.102.3', 50713) to None: 35 bytes
 150.5  12 | 2018-11-05T15:11:33+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 150.5  12 | 2018-11-05T15:11:33+0000 [stdout#info] A query: b'fedoraproject.org'
 150.5  19 | c : DNS request from ('10.100.102.3', 36292) to None: 47 bytes
 150.5  12 | 2018-11-05T15:11:33+0000 [stdout#info] AAAA query, sending back A instead: b'fedoraproject.org'
 150.5  12 | 2018-11-05T15:11:33+0000 [stdout#info] A query: b'fedoraproject.org'
 150.5  12 | 2018-11-05T15:11:33+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 150.5  19 | c : DNS request from ('10.100.102.3', 36292) to None: 47 bytes
 150.5  19 | c : SW#19:10.100.102.3:34334: deleting (15 remain)
 150.5  19 | c : SW#19:10.100.102.3:34334: error was: uread: [Errno 104] Connection reset by peer
 150.5  19 | c : SW'unknown':Mux#233: deleting (14 remain)
 150.5  19 | c : SW#10:10.100.102.3:34332: deleting (13 remain)
 150.5  19 | c : SW#10:10.100.102.3:34332: error was: uread: [Errno 104] Connection reset by peer
 150.5  19 | c : SW'unknown':Mux#232: deleting (12 remain)
 150.5  19 | c : SW#12:10.100.102.3:34350: deleting (11 remain)
 150.5  19 | c : SW#12:10.100.102.3:34350: error was: uread: [Errno 104] Connection reset by peer
 150.5  19 | c : SW'unknown':Mux#235: deleting (10 remain)
 150.6  12 | 2018-11-05T15:11:33+0000 [stdout#info] Updated query of type 1 from b'fedoraproject.org.localdomain' to b'fedoraproject.org'
 150.6  12 | 2018-11-05T15:11:33+0000 [stdout#info] A query: b'fedoraproject.org'
 150.6  12 | 2018-11-05T15:11:33+0000 [stdout#info] Updated query of type 28 from b'fedoraproject.org.localdomain' to b'fedoraproject.org'
 150.6  12 | 2018-11-05T15:11:33+0000 [stdout#info] AAAA query, sending back A instead: b'fedoraproject.org'
 150.6  12 | 2018-11-05T15:11:33+0000 [stdout#info] A query: b'fedoraproject.org'
 151.1 TEL | [35] Running: sudo -n echo -n
 151.5  19 | c : DNS request from ('10.100.102.3', 60816) to None: 33 bytes
 151.5  19 | c : DNS request from ('10.100.102.3', 36125) to None: 35 bytes
 151.5  12 | 2018-11-05T15:11:34+0000 [stdout#info] A query: b'ssl.gstatic.com'
 151.5  12 | 2018-11-05T15:11:34+0000 [stdout#info] A query: b'0.docs.google.com'
 151.6  12 | 2018-11-05T15:11:34+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 151.6  19 | c : DNS request from ('10.100.102.3', 37705) to None: 45 bytes
 151.6  12 | 2018-11-05T15:11:34+0000 [stdout#info] Updated query of type 1 from b'ssl.gstatic.com.localdomain' to b'ssl.gstatic.com'
 151.6  12 | 2018-11-05T15:11:34+0000 [stdout#info] A query: b'ssl.gstatic.com'
 151.7  12 | 2018-11-05T15:11:34+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 151.7  19 | c : DNS request from ('10.100.102.3', 47826) to None: 47 bytes
 151.7 TEL | (proxy checking local liveness)
 151.7  12 | 2018-11-05T15:11:34+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 151.7  12 | 2018-11-05T15:11:34+0000 [stdout#info] A query: b'0.docs.google.com'
 151.7  12 | 2018-11-05T15:11:34+0000 [Poll#info] Checkpoint
 151.7  12 | 2018-11-05T15:11:34+0000 [-] Unhandled Error
 151.7  12 | 	Traceback (most recent call last):
 151.7  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 1, 1)]
 151.7  12 | 
 151.7  12 | 2018-11-05T15:11:34+0000 [-] Unhandled Error
 151.7  12 | 	Traceback (most recent call last):
 151.7  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 1, 1)]
 151.7  12 | 
 151.7  12 | 2018-11-05T15:11:34+0000 [-] (UDP Port 33935 Closed)
 151.7  12 | 2018-11-05T15:11:34+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672769b0>
 151.8  12 | 2018-11-05T15:11:35+0000 [-] Unhandled Error
 151.8  12 | 	Traceback (most recent call last):
 151.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 28, 1)]
 151.8  12 | 
 151.8  12 | 2018-11-05T15:11:35+0000 [-] Unhandled Error
 151.8  12 | 	Traceback (most recent call last):
 151.8  12 | 	Failure: twisted.internet.defer.TimeoutError: [Query('cups.tlv.redhat.com.localdomain', 28, 1)]
 151.8  12 | 
 151.8  12 | 2018-11-05T15:11:35+0000 [-] (UDP Port 59239 Closed)
 151.8  12 | 2018-11-05T15:11:35+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672767b8>
 152.5  19 | c : DNS request from ('10.100.102.3', 54502) to None: 35 bytes
 152.5  19 | c : DNS request from ('10.100.102.3', 38948) to None: 33 bytes
 152.5  12 | 2018-11-05T15:11:35+0000 [stdout#info] A query: b'0.docs.google.com'
 152.5  12 | 2018-11-05T15:11:35+0000 [stdout#info] A query: b'ssl.gstatic.com'
 152.6  12 | 2018-11-05T15:11:35+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 152.6  12 | 2018-11-05T15:11:35+0000 [stdout#info] Failed to lookup b'ssl.gstatic.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 152.6  12 | 2018-11-05T15:11:35+0000 [stdout#info] ], falling back to b'ssl.gstatic.com.localdomain'
 152.7  12 | 2018-11-05T15:11:35+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 152.7  12 | 2018-11-05T15:11:35+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 152.7  12 | 2018-11-05T15:11:35+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
 155.5  12 | 2018-11-05T15:11:38+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 155.5  19 | c : DNS request from ('10.100.102.3', 36292) to None: 47 bytes
 155.5  19 | c : DNS request from ('10.100.102.3', 36292) to None: 47 bytes
 155.5  12 | 2018-11-05T15:11:38+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 155.5  12 | 2018-11-05T15:11:38+0000 [stdout#info] Updated query of type 1 from b'fedoraproject.org.localdomain' to b'fedoraproject.org'
 155.5  12 | 2018-11-05T15:11:38+0000 [stdout#info] A query: b'fedoraproject.org'
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] Updated query of type 28 from b'fedoraproject.org.localdomain' to b'fedoraproject.org'
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] AAAA query, sending back A instead: b'fedoraproject.org'
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] A query: b'fedoraproject.org'
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] Failed to lookup b'fedoraproject.org' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] ], falling back to b'fedoraproject.org.localdomain'
 155.6  12 | 2018-11-05T15:11:38+0000 [-] DNSDatagramProtocol starting on 15594
 155.6  12 | 2018-11-05T15:11:38+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6780>
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] Failed to lookup b'fedoraproject.org' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 155.6  12 | 2018-11-05T15:11:38+0000 [stdout#info] ], falling back to b'fedoraproject.org.localdomain'
 155.6  12 | 2018-11-05T15:11:38+0000 [-] DNSDatagramProtocol starting on 62610
 155.6  12 | 2018-11-05T15:11:38+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e6a0>
 156.5  19 | c : DNS request from ('10.100.102.3', 47013) to None: 37 bytes
 156.5  19 | c : DNS request from ('10.100.102.3', 47013) to None: 37 bytes
 156.5  12 | 2018-11-05T15:11:39+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
 156.5  12 | 2018-11-05T15:11:39+0000 [stdout#info] AAAA query, sending back A instead: b'cups.tlv.redhat.com'
 156.5  12 | 2018-11-05T15:11:39+0000 [stdout#info] A query: b'cups.tlv.redhat.com'
 156.5  12 | 2018-11-05T15:11:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 156.6  19 | c : DNS request from ('10.100.102.3', 37705) to None: 45 bytes
 156.6  12 | 2018-11-05T15:11:39+0000 [stdout#info] Updated query of type 1 from b'ssl.gstatic.com.localdomain' to b'ssl.gstatic.com'
 156.6  12 | 2018-11-05T15:11:39+0000 [stdout#info] A query: b'ssl.gstatic.com'
 156.6  12 | 2018-11-05T15:11:39+0000 [-] DNSDatagramProtocol starting on 36813
 156.6  12 | 2018-11-05T15:11:39+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671dd9b0>
 156.6  12 | 2018-11-05T15:11:39+0000 [-] (UDP Port 15594 Closed)
 156.6  12 | 2018-11-05T15:11:39+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671e6780>
 156.6  12 | 2018-11-05T15:11:39+0000 [-] DNSDatagramProtocol starting on 9665
 156.6  12 | 2018-11-05T15:11:39+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672ab160>
 156.6  12 | 2018-11-05T15:11:39+0000 [-] (UDP Port 62610 Closed)
 156.6  12 | 2018-11-05T15:11:39+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa86728e6a0>
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 156.7  19 | c : DNS request from ('10.100.102.3', 47826) to None: 47 bytes
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] Failed to lookup b'ssl.gstatic.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] ], falling back to b'ssl.gstatic.com.localdomain'
 156.7  12 | 2018-11-05T15:11:39+0000 [-] DNSDatagramProtocol starting on 22522
 156.7  12 | 2018-11-05T15:11:39+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8671c7d68>
 156.7  12 | 2018-11-05T15:11:39+0000 [-] (UDP Port 42016 Closed)
 156.7  12 | 2018-11-05T15:11:39+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fa8672e58d0>
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] Updated query of type 1 from b'0.docs.google.com.localdomain' to b'0.docs.google.com'
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] A query: b'0.docs.google.com'
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] getaddrinfo error: [Errno -3] Try again
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] Failed to lookup b'0.docs.google.com' due to [Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DomainError'>: [Errno -3] Try again
 156.7  12 | 2018-11-05T15:11:39+0000 [stdout#info] ], falling back to b'0.docs.google.com.localdomain'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         